// Contenido del grado 10° (Estándares MEN 2004, DBA 2016)
import type { Grade } from './types';
const grade: Grade = 
{id:'g10',n:10,title:'Química inorgánica',desc:'Estructura atómica, enlace, nomenclatura y estequiometría.',units:[
{id:'g10u1',title:'Estructura atómica',desc:'Configuración electrónica, orbitales e isótopos.',lessons:[
 {id:'g10u1l1',title:'Configuración electrónica',time:55,std:'Explico la estructura de los átomos a partir de diferentes teorías.',dba:'',
  body:['Los electrones se ubican en <b>niveles</b> (1, 2, 3…) y <b>subniveles</b> (s, p, d, f). El subnivel s admite 2 electrones, p admite 6, d admite 10 y f admite 14.',
   'Se llenan en orden de energía (principio de Aufbau, o regla de las diagonales): 1s 2s 2p 3s 3p 4s 3d 4p…',
   'Los electrones del nivel más externo son los <b>electrones de valencia</b>. Ellos determinan cómo se enlaza el átomo. Ejemplo: oxígeno (Z = 8) → 1s² 2s² 2p⁴, con 6 electrones de valencia.'],
  key:'La configuración dice dónde están los electrones; los de valencia dicen cómo reacciona el átomo.',
  co:'',
  act:{type:'config',prompt:'Mueve el número atómico y observa cómo se llenan los orbitales.',start:8,ask:[{q:'¿Cuántos electrones de valencia tiene el azufre (Z = 16)?',a:6,tol:0},{q:'¿En qué periodo está el potasio (Z = 19)?',a:4,tol:0},{q:'¿Qué subnivel se llena después del 4s?',o:['4p','3d','4d','3f'],a:1,e:'Por eso aparecen los metales de transición en el periodo 4.'}]},
  quiz:[{q:'La configuración del sodio (Z = 11) es…',o:['1s² 2s² 2p⁶ 3s¹','1s² 2s² 2p⁷','1s² 2s² 3s² 2p⁵'],a:0,e:'Once electrones siguiendo el orden de Aufbau.'},
   {q:'¿Cuántos electrones caben en un subnivel p?',o:['2','6','10','14'],a:1,e:'Tres orbitales con dos electrones cada uno.'},
   {q:'El cloro (1s² 2s² 2p⁶ 3s² 3p⁵) tiene … electrones de valencia.',o:['5','7','17','2'],a:1,e:'3s² + 3p⁵ = 7.'}]},
 {id:'g10u1l2',title:'Orbitales y regla de Hund',time:50,std:'Explico la estructura de los átomos a partir de diferentes teorías.',dba:'',
  body:['Un <b>orbital</b> es una región donde es muy probable encontrar un electrón. Cada orbital admite máximo 2 electrones con espín opuesto (principio de exclusión de Pauli).',
   'Según la <b>regla de Hund</b>, en un subnivel los electrones ocupan primero orbitales vacíos, uno en cada uno, antes de aparearse.',
   'Los electrones desapareados explican propiedades como el magnetismo y cuántos enlaces puede formar un átomo.'],
  key:'Primero uno por caja, luego se aparean.',
  co:'',
  act:{type:'config',prompt:'Observa el diagrama de cajas (↑↓) del nitrógeno, el oxígeno y el hierro.',start:7,ask:[{q:'¿Cuántos electrones desapareados tiene el nitrógeno (Z = 7) en el 2p?',a:3,tol:0},{q:'¿Cuántos electrones desapareados tiene el oxígeno (Z = 8) en el 2p?',a:2,tol:0}]},
  quiz:[{q:'Un orbital puede tener como máximo…',o:['1 electrón','2 electrones','6 electrones'],a:1,e:'Principio de exclusión de Pauli.'},
   {q:'La regla de Hund dice que…',o:['Los electrones se aparean primero','Se llenan orbitales vacíos antes de aparear','Los electrones no tienen espín'],a:1,e:'Minimiza la repulsión entre electrones.'},
   {q:'El carbono (2p²) tiene en el 2p…',o:['Dos electrones apareados','Dos electrones desapareados','Ningún electrón'],a:1,e:'Uno en cada orbital.'}]},
 {id:'g10u1l3',title:'Isótopos y energía nuclear',time:55,std:'Explico la obtención de energía nuclear a partir de la alteración de la estructura del átomo.',dba:'',
  body:['Los <b>isótopos</b> son átomos del mismo elemento con distinto número de neutrones: carbono-12 y carbono-14 tienen 6 protones, pero 6 y 8 neutrones.',
   'Algunos isótopos son <b>radiactivos</b>: su núcleo es inestable y se transforma emitiendo radiación. El tiempo en que se desintegra la mitad se llama <b>vida media</b>.',
   'En la <b>fisión nuclear</b> un núcleo pesado se parte y libera mucha energía. Así funcionan las centrales nucleares. En la <b>fusión</b>, núcleos livianos se unen, como en el Sol.'],
  key:'Mismo número de protones, distinto número de neutrones: isótopos.',
  co:'En hospitales colombianos se usa el yodo-131 para tratar enfermedades de la tiroides y el tecnecio-99m para diagnóstico.',
  act:{type:'atom',prompt:'Construye estos isótopos e iones.',start:{p:6,n:6,e:6},targets:[{p:6,n:8,e:6,label:'Carbono-14 (isótopo radiactivo)'},{p:1,n:1,e:1,label:'Deuterio (hidrógeno-2)'},{p:11,n:12,e:10,label:'Ion sodio Na⁺'},{p:17,n:18,e:18,label:'Ion cloruro Cl⁻'}]},
  quiz:[{q:'El carbono-14 tiene…',o:['14 protones','8 neutrones','14 electrones'],a:1,e:'14 − 6 = 8 neutrones.'},
   {q:'Si la vida media de un isótopo es 8 días, de 100 g quedan después de 16 días…',o:['50 g','25 g','0 g','12,5 g'],a:1,e:'Dos vidas medias: 100 → 50 → 25 g.'},
   {q:'La energía del Sol proviene de…',o:['Fisión','Fusión','Combustión'],a:1,e:'Núcleos de hidrógeno se fusionan en helio.'}]}
]},
{id:'g10u2',title:'Enlace químico',desc:'Por qué y cómo se unen los átomos.',lessons:[
 {id:'g10u2l1',title:'Regla del octeto y estructuras de Lewis',time:55,std:'Explico la relación entre la estructura de los átomos y los enlaces que realiza.',dba:'',
  body:['Los átomos tienden a completar <b>8 electrones</b> en su capa externa (el hidrógeno, 2). Lo logran ganando, perdiendo o compartiendo electrones.',
   'En una <b>estructura de Lewis</b> se dibujan los electrones de valencia como puntos. Un par compartido es un enlace; los pares que no se comparten son <b>pares libres</b>.',
   'En el agua, el oxígeno comparte 2 pares (con los H) y conserva 2 pares libres: 8 electrones en total.'],
  key:'Enlaces + pares libres = octeto completo.',
  co:'',
  act:{type:'mol3d',prompt:'Activa los pares libres y cuenta los electrones alrededor del átomo central.',lp:true,mols:['H2O','NH3','CH4','HCl']},
  quiz:[{q:'¿Cuántos pares libres tiene el oxígeno en el H₂O?',o:['0','1','2','3'],a:2,e:'2 enlaces + 2 pares libres = 8 electrones.'},
   {q:'El nitrógeno del NH₃ tiene…',o:['3 enlaces y 1 par libre','4 enlaces','2 enlaces y 2 pares libres'],a:0,e:'5 electrones de valencia: 3 compartidos + 2 en el par libre.'},
   {q:'¿Cuál NO cumple el octeto?',o:['CH₄','BF₃','H₂O','NH₃'],a:1,e:'El boro queda con 6 electrones.'}]},
 {id:'g10u2l2',title:'Enlace iónico, covalente y metálico',time:55,std:'Explico la relación entre la estructura de los átomos y los enlaces que realiza.',dba:'',
  body:['La diferencia de <b>electronegatividad (ΔEN)</b> ayuda a predecir el enlace. Si ΔEN es mayor que 1,7, un átomo le quita electrones al otro: <b>enlace iónico</b> (NaCl).',
   'Si ΔEN está entre 0,4 y 1,7, los electrones se comparten de forma desigual: <b>covalente polar</b> (H₂O, HCl). Si es menor que 0,4, se comparten por igual: <b>covalente apolar</b> (O₂, CH₄).',
   'En el <b>enlace metálico</b>, los metales comparten un “mar” de electrones libres. Por eso conducen la electricidad.'],
  key:'Mucha diferencia de electronegatividad: iónico. Poca: covalente.',
  co:'El cobre de las redes eléctricas conduce gracias al enlace metálico.',
  act:{type:'classify',prompt:'Clasifica el enlace según la diferencia de electronegatividad (usa: Na 0,9; Cl 3,2; H 2,2; O 3,4; C 2,5; K 0,8; F 4,0).',bins:['Iónico','Covalente polar','Covalente apolar'],items:[['NaCl',0],['H₂O',1],['O₂',2],['KF',0],['HCl',1],['CH₄ (C–H)',2],['Cl₂',2]]},
  quiz:[{q:'Para el enlace Na–Cl, ΔEN ≈ 2,1. El enlace es…',o:['Iónico','Covalente polar','Covalente apolar'],a:0,e:'Mayor que 1,7.'},
   {q:'Los metales conducen la electricidad porque…',o:['Tienen enlace iónico','Tienen electrones libres que se mueven','Son sólidos'],a:1,e:'Es el modelo del mar de electrones.'},
   {q:'En el HCl, los electrones compartidos están más cerca de…',o:['El hidrógeno','El cloro','En el centro exacto'],a:1,e:'El cloro es más electronegativo.'}]},
 {id:'g10u2l3',title:'Geometría molecular',time:55,std:'Explico la relación entre la estructura de los átomos y los enlaces que realiza.',dba:'',
  body:['Según la teoría <b>RPECV</b> (repulsión de pares de electrones de la capa de valencia), los pares de electrones se alejan lo más posible.',
   'Cuatro pares sin pares libres forman un <b>tetraedro</b> (CH₄, 109,5°). Si uno es par libre: <b>piramidal</b> (NH₃, 107°). Si son dos pares libres: <b>angular</b> (H₂O, 104,5°).',
   'Tres pares sin pares libres forman una geometría <b>trigonal plana</b> (BF₃, 120°). Dos pares: <b>lineal</b> (CO₂, 180°). La geometría decide si una molécula es polar.'],
  key:'Los pares libres empujan más que los enlaces y cierran los ángulos.',
  co:'',
  act:{type:'mol3d',prompt:'Compara las cinco geometrías. Activa los pares libres.',lp:true,mols:['CO2','BF3','CH4','NH3','H2O']},
  quiz:[{q:'¿Qué geometría tiene el BF₃?',o:['Tetraédrica','Trigonal plana','Piramidal','Angular'],a:1,e:'Tres enlaces, sin pares libres, a 120°.'},
   {q:'¿Por qué el CO₂ es apolar si sus enlaces son polares?',o:['Porque es lineal y los efectos se cancelan','Porque no tiene oxígeno','Porque es un gas'],a:0,e:'Simetría lineal.'},
   {q:'El ángulo del agua es menor que 109,5° porque…',o:['Los pares libres repelen más','El oxígeno es pequeño','Hay enlaces dobles'],a:0,e:'Los pares libres ocupan más espacio.'}]}
]},
{id:'g10u3',title:'Nomenclatura inorgánica',desc:'Óxidos, hidróxidos, ácidos y sales.',lessons:[
 {id:'g10u3l1',title:'Óxidos',time:50,std:'Uso la tabla periódica para determinar propiedades físicas y químicas de los elementos.',dba:'DBA 10°: comprende que los diferentes mecanismos de reacción química posibilitan la formación de compuestos inorgánicos.',
  body:['Un <b>óxido</b> es un compuesto de oxígeno con otro elemento.',
   'Metal + oxígeno → <b>óxido básico</b> (CaO, óxido de calcio). No metal + oxígeno → <b>óxido ácido</b> (CO₂, dióxido de carbono).',
   'En la nomenclatura sistemática se usan prefijos: mono-, di-, tri-, penta-. En la de Stock se indica el número de oxidación del metal en romanos: Fe₂O₃ = óxido de hierro (III).'],
  key:'Metal + O: óxido básico. No metal + O: óxido ácido.',
  co:'La cal viva (CaO) se usa en Boyacá y Cundinamarca para corregir suelos ácidos.',
  act:{type:'classify',prompt:'¿Óxido básico u óxido ácido?',bins:['Óxido básico','Óxido ácido'],items:[['CaO',0],['CO₂',1],['Fe₂O₃',0],['SO₃',1],['Na₂O',0],['NO₂',1],['MgO',0],['P₂O₅',1]]},
  quiz:[{q:'El Na₂O es un óxido…',o:['Básico','Ácido'],a:0,e:'El sodio es metal.'},
   {q:'Nombre sistemático del SO₃:',o:['Monóxido de azufre','Trióxido de azufre','Óxido de azufre (II)'],a:1,e:'Tres oxígenos: trióxido.'},
   {q:'Fe₂O₃ en Stock es…',o:['Óxido de hierro (II)','Óxido de hierro (III)','Trióxido de hierro'],a:1,e:'Cada hierro tiene número de oxidación +3.'}]},
 {id:'g10u3l2',title:'Hidróxidos y ácidos',time:55,std:'Explico los cambios químicos desde diferentes modelos.',dba:'DBA 10°: comprende que los diferentes mecanismos de reacción química posibilitan la formación de compuestos inorgánicos.',
  body:['Óxido básico + agua → <b>hidróxido</b> (base): CaO + H₂O → Ca(OH)₂, hidróxido de calcio. Tienen el grupo OH.',
   'Óxido ácido + agua → <b>oxácido</b>: SO₃ + H₂O → H₂SO₄, ácido sulfúrico. Contienen H, un no metal y O.',
   'Los <b>hidrácidos</b> no tienen oxígeno: H + no metal disuelto en agua, como HCl (ácido clorhídrico).'],
  key:'Hidróxido: tiene OH. Oxácido: H + no metal + O. Hidrácido: H + no metal.',
  co:'',
  act:{type:'classify',prompt:'Clasifica cada compuesto.',bins:['Hidróxido','Oxácido','Hidrácido'],items:[['NaOH',0],['H₂SO₄',1],['HCl',2],['Ca(OH)₂',0],['HNO₃',1],['H₂S',2],['Al(OH)₃',0],['H₂CO₃',1]]},
  quiz:[{q:'El HNO₃ es un…',o:['Hidróxido','Oxácido','Hidrácido'],a:1,e:'Tiene H, N y O.'},
   {q:'CaO + H₂O produce…',o:['CaCO₃','Ca(OH)₂','H₂CO₃'],a:1,e:'Óxido básico + agua = hidróxido.'},
   {q:'El ácido del estómago, HCl, es un…',o:['Oxácido','Hidrácido','Hidróxido'],a:1,e:'No tiene oxígeno.'}]},
 {id:'g10u3l3',title:'Sales',time:50,std:'Explico los cambios químicos desde diferentes modelos.',dba:'DBA 10°: comprende que los diferentes mecanismos de reacción química posibilitan la formación de compuestos inorgánicos.',
  body:['Una <b>sal</b> se forma cuando un ácido reacciona con una base. El metal de la base reemplaza al hidrógeno del ácido.',
   'Si el ácido es un hidrácido se forma una <b>sal haloidea</b> (terminación -uro): NaCl, cloruro de sodio. Si es un oxácido se forma una <b>oxisal</b> (terminaciones -ato o -ito): CaCO₃, carbonato de calcio.',
   'Regla práctica: -hídrico pasa a -uro, -ico pasa a -ato y -oso pasa a -ito.'],
  key:'Ácido + base → sal + agua. -uro, -ato, -ito.',
  co:'El carbonato de calcio (CaCO₃) forma las cavernas de mármol y piedra caliza de Santander.',
  act:{type:'classify',prompt:'¿Sal haloidea u oxisal?',bins:['Sal haloidea (-uro)','Oxisal (-ato / -ito)'],items:[['NaCl',0],['CaCO₃',1],['KBr',0],['Na₂SO₄',1],['CaF₂',0],['KNO₃',1],['FeS',0],['NaNO₂',1]]},
  quiz:[{q:'El nombre del KNO₃ es…',o:['Nitruro de potasio','Nitrato de potasio','Nitrito de potasio'],a:1,e:'Viene del ácido nítrico (-ico → -ato).'},
   {q:'HCl + NaOH forma…',o:['Cloruro de sodio y agua','Clorato de sodio','Hidróxido de cloro'],a:0,e:'Sal haloidea.'},
   {q:'El CaCO₃ es una…',o:['Sal haloidea','Oxisal','Base'],a:1,e:'Contiene oxígeno del ácido carbónico.'}]}
]},
{id:'g10u4',title:'Reacciones y estequiometría',desc:'Tipos de reacción y cálculos con cantidades.',lessons:[
 {id:'g10u4l1',title:'Tipos de reacciones',time:50,std:'Explico los cambios químicos desde diferentes modelos.',dba:'DBA 10°: comprende que los diferentes mecanismos de reacción química (óxido-reducción, descomposición, neutralización y precipitación) posibilitan la formación de compuestos inorgánicos.',
  body:['<b>Síntesis</b>: A + B → AB. <b>Descomposición</b>: AB → A + B. <b>Desplazamiento simple</b>: A + BC → AC + B. <b>Doble desplazamiento</b>: AB + CD → AD + CB, que incluye la neutralización y la precipitación.',
   'En las reacciones de <b>óxido-reducción</b> hay transferencia de electrones: una especie se oxida (pierde electrones) y otra se reduce (los gana). La combustión y la corrosión son redox.'],
  key:'Unir, separar, reemplazar o intercambiar. Si cambian los números de oxidación, es redox.',
  co:'',
  act:{type:'classify',prompt:'Clasifica cada reacción.',bins:['Síntesis','Descomposición','Desplazamiento simple','Doble desplazamiento'],items:[['2 H₂ + O₂ → 2 H₂O',0],['CaCO₃ → CaO + CO₂',1],['Zn + 2 HCl → ZnCl₂ + H₂',2],['HCl + NaOH → NaCl + H₂O',3],['N₂ + 3 H₂ → 2 NH₃',0],['2 H₂O₂ → 2 H₂O + O₂',1],['AgNO₃ + NaCl → AgCl + NaNO₃',3]]},
  quiz:[{q:'CaCO₃ → CaO + CO₂ es una…',o:['Síntesis','Descomposición','Neutralización'],a:1,e:'Un compuesto se separa en dos.'},
   {q:'En una oxidación, un átomo…',o:['Gana electrones','Pierde electrones','Gana protones'],a:1,e:'Oxidación = pérdida de electrones.'},
   {q:'La formación de un sólido al mezclar dos soluciones se llama…',o:['Precipitación','Combustión','Síntesis'],a:0,e:'Un tipo de doble desplazamiento.'}]},
 {id:'g10u4l2',title:'Mol y masa molar',time:50,std:'Realizo cálculos cuantitativos en cambios químicos.',dba:'',
  body:['Para contar átomos usamos el <b>mol</b> (6,02 × 10²³ partículas). La <b>masa molar</b> se obtiene sumando masas atómicas.',
   'Conversión clave: <b>moles = masa ÷ masa molar</b>.',
   'Ejemplo: 49 g de H₂SO₄ (masa molar 98 g/mol) son 0,5 mol.'],
  key:'Masa ↔ moles, siempre a través de la masa molar.',
  co:'',
  act:{type:'calc',prompt:'¿Cuántos moles hay en 100 g de carbonato de calcio (CaCO₃)?',data:'Masas atómicas: Ca = 40, C = 12, O = 16.',steps:[{q:'Masa molar del CaCO₃',help:'40 + 12 + 3 × 16',unit:'g/mol',ans:100,how:'40 + 12 + 48 = 100 g/mol'},{q:'Moles en 100 g',help:'masa ÷ masa molar',unit:'mol',ans:1,how:'100 ÷ 100 = 1 mol'},{q:'¿Cuántos átomos de oxígeno hay? (número que multiplica a 10²³)',help:'1 mol × 3 átomos de O × 6,02',unit:'× 10²³',ans:18.06,tol:.05,how:'3 × 6,02 × 10²³ = 18,06 × 10²³'}]},
  quiz:[{q:'La masa molar del NaOH (Na 23, O 16, H 1) es…',o:['40 g/mol','39 g/mol','24 g/mol'],a:0,e:'23 + 16 + 1.'},
   {q:'¿Cuántos moles son 88 g de CO₂?',o:['1','2','4'],a:1,e:'88 ÷ 44 = 2 mol.'},
   {q:'1 mol de O₂ tiene … átomos de oxígeno.',o:['6,02 × 10²³','12,04 × 10²³','16'],a:1,e:'Cada molécula tiene 2 átomos.'}]},
 {id:'g10u4l3',title:'Estequiometría y reactivo límite',time:60,std:'Realizo cálculos cuantitativos en cambios químicos.',dba:'',
  body:['La <b>estequiometría</b> usa los coeficientes de la ecuación balanceada como proporciones: en CH₄ + 2 O₂ → CO₂ + 2 H₂O, 1 mol de metano produce 1 mol de CO₂.',
   'Pasos: masa → moles → proporción de coeficientes → moles del producto → masa.',
   'El <b>reactivo límite</b> es el que se acaba primero y determina cuánto producto se forma. El otro queda en exceso.'],
  key:'Masa → moles → coeficientes → moles → masa.',
  co:'En la refinería de Barrancabermeja se calcula cuánto combustible y aire se necesitan en cada proceso con estas mismas proporciones.',
  act:{type:'calc',prompt:'Se queman 32 g de metano (CH₄ + 2 O₂ → CO₂ + 2 H₂O). ¿Cuántos gramos de agua se producen?',data:'H = 1, C = 12, O = 16.',steps:[{q:'Masa molar del CH₄',unit:'g/mol',ans:16,how:'12 + 4 = 16 g/mol'},{q:'Moles de CH₄',help:'32 ÷ 16',unit:'mol',ans:2,how:'2 mol'},{q:'Moles de H₂O',help:'Por cada 1 mol de CH₄ se forman 2 de H₂O',unit:'mol',ans:4,how:'2 × 2 = 4 mol'},{q:'Masa de H₂O',help:'moles × 18 g/mol',unit:'g',ans:72,how:'4 × 18 = 72 g'}]},
  quiz:[{q:'En 2 H₂ + O₂ → 2 H₂O, si tienes 4 mol de H₂ y 1 mol de O₂, el reactivo límite es…',o:['H₂','O₂','Ninguno'],a:1,e:'4 mol de H₂ necesitarían 2 mol de O₂; solo hay 1.'},
   {q:'Los coeficientes de una ecuación balanceada indican relaciones de…',o:['Gramos','Moles','Volumen siempre'],a:1,e:'Son proporciones molares.'},
   {q:'¿Cuántos moles de NH₃ se forman con 3 mol de N₂ (N₂ + 3 H₂ → 2 NH₃) si hay H₂ suficiente?',o:['3','6','2','9'],a:1,e:'1 : 2, entonces 3 × 2 = 6 mol.'}]}
]}
]};
export default grade;
