// Contenido del grado 11° (Estándares MEN 2004, DBA 2016)
import type { Grade } from './types';
const grade: Grade = 
{id:'g11',n:11,title:'Química orgánica y fisicoquímica',desc:'Velocidad de reacción, equilibrio, el carbono y sus compuestos.',units:[
{id:'g11u1',title:'Cinética y equilibrio',desc:'Qué tan rápido ocurre una reacción y hasta dónde llega.',lessons:[
 {id:'g11u1l1',title:'Velocidad de reacción',time:55,std:'Identifico condiciones para controlar la velocidad de cambios químicos.',dba:'',
  body:['Según la <b>teoría de colisiones</b>, para reaccionar las partículas deben chocar con suficiente energía (la <b>energía de activación</b>) y con la orientación adecuada.',
   'La velocidad aumenta con la <b>temperatura</b> (choques más frecuentes y energéticos), la <b>concentración</b> (más partículas), la <b>superficie de contacto</b> (sólidos en polvo) y los <b>catalizadores</b>, que bajan la energía de activación sin consumirse.'],
  key:'Más choques efectivos, reacción más rápida.',
  co:'La nevera conserva los alimentos porque el frío hace más lentas las reacciones de descomposición. Las enzimas del cuerpo son catalizadores naturales.',
  act:{type:'rate',prompt:'Cambia temperatura, concentración y catalizador. Observa los choques efectivos (verde).',ask:[{q:'Al subir la temperatura, la velocidad de reacción…',o:['Aumenta','Disminuye','No cambia'],a:0},{q:'El catalizador acelera la reacción porque…',o:['Aumenta la temperatura','Disminuye la energía de activación','Agrega más reactivos'],a:1},{q:'Con más concentración, los choques efectivos…',o:['Aumentan','Disminuyen'],a:0}]},
  quiz:[{q:'¿Por qué una panela en polvo se disuelve más rápido que en bloque?',o:['Tiene más azúcar','Tiene más superficie de contacto','Está más fría'],a:1,e:'Más área expuesta, más choques.'},
   {q:'Un catalizador…',o:['Se consume en la reacción','Baja la energía de activación y se recupera','Cambia los productos'],a:1,e:'Abre un camino más fácil.'},
   {q:'La energía de activación es…',o:['La energía mínima para que un choque produzca reacción','La energía liberada','La temperatura de ebullición'],a:0,e:'Es la “barrera” que hay que superar.'}]},
 {id:'g11u1l2',title:'Equilibrio químico y Le Châtelier',time:60,std:'Caracterizo cambios químicos en condiciones de equilibrio.',dba:'',
  body:['Muchas reacciones son <b>reversibles</b>: los productos también reaccionan para volver a formar reactivos. Se llega al <b>equilibrio</b> cuando ambas velocidades son iguales y las concentraciones dejan de cambiar.',
   'El <b>principio de Le Châtelier</b> dice que si se perturba un sistema en equilibrio, este se desplaza para contrarrestar el cambio.',
   'Si agregas un reactivo, se forma más producto. Si aumentas la presión, se favorece el lado con menos moléculas de gas. Si calientas una reacción exotérmica, se favorecen los reactivos.'],
  key:'El equilibrio “se defiende”: se desplaza en contra de la perturbación.',
  co:'Los fertilizantes nitrogenados que usan los cultivos de flores de la Sabana dependen del proceso Haber, que se diseñó aplicando este principio.',
  act:{type:'equil',prompt:'Perturba el equilibrio del proceso Haber y observa hacia dónde se desplaza.',ask:[{q:'Al aumentar la presión, el equilibrio se desplaza hacia…',o:['Los reactivos','Los productos (NH₃)'],a:1,e:'Hay 4 moléculas de gas a la izquierda y 2 a la derecha.'},{q:'Al calentar esta reacción exotérmica, se favorecen…',o:['Los reactivos','Los productos'],a:0},{q:'Si retiras NH₃ a medida que se forma…',o:['Se forma más NH₃','Se forma menos NH₃'],a:0}]},
  quiz:[{q:'En el equilibrio químico…',o:['La reacción se detiene','Las velocidades directa e inversa son iguales','Solo hay productos'],a:1,e:'Es un equilibrio dinámico.'},
   {q:'Para N₂ + 3 H₂ ⇌ 2 NH₃, disminuir la presión favorece…',o:['Los productos','Los reactivos'],a:1,e:'El lado con más moléculas de gas.'},
   {q:'Agregar un catalizador al equilibrio…',o:['Lo desplaza a los productos','No lo desplaza, solo lo alcanza más rápido','Lo desplaza a los reactivos'],a:1,e:'Acelera ambas direcciones por igual.'}]}
]},
{id:'g11u2',title:'El carbono y los hidrocarburos',desc:'Por qué el carbono forma millones de compuestos.',lessons:[
 {id:'g11u2l1',title:'El átomo de carbono e hibridación',time:55,std:'Relaciono la estructura del carbono con la formación de moléculas orgánicas.',dba:'DBA 11°: comprende que los diferentes mecanismos de reacción química posibilitan la formación de distintos tipos de compuestos orgánicos.',
  body:['El carbono tiene 4 electrones de valencia y forma <b>4 enlaces</b>. Puede unirse a otros carbonos formando cadenas y anillos: por eso existen millones de compuestos orgánicos.',
   'Según sus enlaces, el carbono presenta <b>hibridación</b>: <b>sp³</b> con cuatro enlaces sencillos (tetraédrico, 109,5°), <b>sp²</b> con un doble enlace (trigonal plano, 120°) y <b>sp</b> con un triple enlace (lineal, 180°).'],
  key:'Sencillo: sp³. Doble: sp². Triple: sp.',
  co:'',
  act:{type:'mol3d',prompt:'Compara la geometría del carbono en las tres moléculas.',mols:['CH4','C2H4','C2H2'],lpToggle:false},
  quiz:[{q:'El carbono del eteno (C₂H₄) tiene hibridación…',o:['sp³','sp²','sp'],a:1,e:'Tiene un doble enlace.'},
   {q:'¿Cuántos enlaces forma normalmente el carbono?',o:['2','3','4','6'],a:2,e:'Cuatro electrones de valencia.'},
   {q:'Una molécula con carbono sp es…',o:['Tetraédrica','Lineal','Angular'],a:1,e:'180°, como el acetileno.'}]},
 {id:'g11u2l2',title:'Hidrocarburos: alcanos, alquenos y alquinos',time:60,std:'Relaciono la estructura del carbono con la formación de moléculas orgánicas.',dba:'DBA 11°: comprende que los diferentes mecanismos de reacción química posibilitan la formación de distintos tipos de compuestos orgánicos.',
  body:['Los <b>hidrocarburos</b> solo tienen C e H. Los <b>alcanos</b> tienen enlaces sencillos (terminación -ano), los <b>alquenos</b> al menos un doble enlace (-eno) y los <b>alquinos</b> al menos un triple enlace (-ino).',
   'El prefijo indica el número de carbonos: met- (1), et- (2), prop- (3), but- (4), pent- (5), hex- (6).',
   'Fórmulas generales: alcanos CₙH₂ₙ₊₂, alquenos CₙH₂ₙ, alquinos CₙH₂ₙ₋₂.'],
  key:'Prefijo = número de carbonos. Terminación = tipo de enlace.',
  co:'El gas de los cilindros que se usa en zonas sin red de gas natural es principalmente propano y butano.',
  act:{type:'mol3d',prompt:'Explora un alcano, un alqueno y un alquino de dos carbonos, y el propano.',mols:['C2H6','C3H8','C2H4','C2H2'],lpToggle:false},
  quiz:[{q:'El C₄H₁₀ se llama…',o:['Butano','Buteno','Propano','Butino'],a:0,e:'4 carbonos, fórmula de alcano.'},
   {q:'¿Cuál es un alqueno?',o:['C₃H₈','C₃H₆','C₃H₄'],a:1,e:'CₙH₂ₙ.'},
   {q:'El etino se usa en soldadura. ¿Qué enlace tiene entre carbonos?',o:['Sencillo','Doble','Triple'],a:2,e:'Terminación -ino.'}]},
 {id:'g11u2l3',title:'Isomería',time:50,std:'Relaciono grupos funcionales con las propiedades físicas y químicas de las sustancias.',dba:'',
  body:['Los <b>isómeros</b> tienen la misma fórmula molecular pero distinta estructura, y por eso propiedades diferentes.',
   'Isomería de <b>cadena</b>: butano (lineal) e isobutano (ramificado), ambos C₄H₁₀. De <b>posición</b>: 1-propanol y 2-propanol. De <b>función</b>: etanol y dimetil éter, ambos C₂H₆O, pero uno es alcohol y el otro éter.'],
  key:'Misma fórmula, distinta estructura: isómeros.',
  co:'',
  act:{type:'classify',prompt:'¿Son isómeros entre sí?',bins:['Sí son isómeros','No son isómeros'],items:[['Butano y metilpropano (C₄H₁₀)',0],['Etanol y dimetil éter (C₂H₆O)',0],['Metano y etano',1],['1-propanol y 2-propanol',0],['Eteno y etino',1],['Propanal y propanona (C₃H₆O)',0]]},
  quiz:[{q:'Dos isómeros tienen igual…',o:['Estructura','Fórmula molecular','Punto de ebullición'],a:1,e:'Cambia el arreglo de los átomos.'},
   {q:'Etanol y dimetil éter son isómeros de…',o:['Cadena','Posición','Función'],a:2,e:'Cambia el grupo funcional.'},
   {q:'¿Tienen las mismas propiedades dos isómeros?',o:['Sí, siempre','No, su estructura distinta cambia sus propiedades'],a:1,e:'El etanol es líquido; el dimetil éter, gas.'}]}
]},
{id:'g11u3',title:'Grupos funcionales',desc:'Alcoholes, aldehídos, cetonas, ácidos, ésteres y aminas.',lessons:[
 {id:'g11u3l1',title:'Alcoholes',time:50,std:'Relaciono grupos funcionales con las propiedades físicas y químicas de las sustancias.',dba:'DBA 11°: comprende que los diferentes mecanismos de reacción química posibilitan la formación de distintos tipos de compuestos orgánicos.',
  body:['Un <b>grupo funcional</b> es un conjunto de átomos que da propiedades características. Los <b>alcoholes</b> tienen el grupo hidroxilo <b>–OH</b> y terminan en -ol.',
   'El –OH forma puentes de hidrógeno: los alcoholes pequeños se disuelven en agua y hierven a temperaturas más altas que los alcanos de tamaño parecido.',
   'El <b>etanol</b> se obtiene por fermentación de azúcares. El <b>metanol</b> es tóxico: puede causar ceguera.'],
  key:'–OH = alcohol. Terminación -ol.',
  co:'La gasolina colombiana lleva etanol producido a partir de caña de azúcar del Valle del Cauca.',
  act:{type:'mol3d',prompt:'Encuentra el grupo –OH en cada molécula y activa los pares libres del oxígeno.',lp:true,mols:['CH3OH','C2H5OH']},
  quiz:[{q:'El grupo funcional de los alcoholes es…',o:['–COOH','–OH','–CHO','–NH₂'],a:1,e:'Hidroxilo.'},
   {q:'El etanol se obtiene industrialmente de…',o:['La fermentación de azúcares','El carbón','El aire'],a:0,e:'Como en la caña de azúcar.'},
   {q:'¿Por qué el metanol es peligroso en licores adulterados?',o:['Es tóxico y puede causar ceguera','Tiene mal sabor','Es más caro'],a:0,e:'Se metaboliza a formaldehído y ácido fórmico.'}]},
 {id:'g11u3l2',title:'Aldehídos y cetonas',time:50,std:'Relaciono grupos funcionales con las propiedades físicas y químicas de las sustancias.',dba:'',
  body:['Ambos tienen el grupo <b>carbonilo C=O</b>. En los <b>aldehídos</b> está al final de la cadena (–CHO, terminación -al). En las <b>cetonas</b> está en medio (terminación -ona).',
   'El metanal (formaldehído) se usa para conservar muestras biológicas. La propanona (acetona) es un solvente, como el quitaesmalte.'],
  key:'C=O al final: aldehído (-al). C=O en medio: cetona (-ona).',
  co:'',
  act:{type:'mol3d',prompt:'Compara dónde está el C=O en cada molécula.',lp:true,mols:['H2CO','C3H6O']},
  quiz:[{q:'La acetona es una…',o:['Cetona','Aldehído','Alcohol'],a:0,e:'Propanona: C=O en el carbono central.'},
   {q:'La terminación de los aldehídos es…',o:['-ol','-al','-ona','-oico'],a:1,e:'Metanal, etanal…'},
   {q:'El grupo carbonilo es…',o:['C=O','–OH','C≡C'],a:0,e:'Presente en aldehídos y cetonas.'}]},
 {id:'g11u3l3',title:'Ácidos carboxílicos, ésteres y aminas',time:55,std:'Relaciono grupos funcionales con las propiedades físicas y químicas de las sustancias.',dba:'',
  body:['Los <b>ácidos carboxílicos</b> tienen el grupo <b>–COOH</b> (terminación -oico). El ácido acético da el sabor al vinagre.',
   'Un ácido + un alcohol forman un <b>éster</b> (–COO–) y agua. Los ésteres dan olor a las frutas.',
   'Las <b>aminas</b> tienen nitrógeno (–NH₂) y son bases orgánicas. Aparecen en las proteínas y en el olor del pescado.'],
  key:'–COOH ácido, –COO– éster, –NH₂ amina.',
  co:'El aroma característico del lulo y la guayaba se debe en parte a ésteres.',
  act:{type:'classify',prompt:'Identifica el grupo funcional.',bins:['Alcohol','Aldehído','Cetona','Ácido carboxílico','Éster','Amina'],items:[['CH₃–OH',0],['CH₃–CHO',1],['CH₃–CO–CH₃',2],['CH₃–COOH',3],['CH₃–COO–CH₃',4],['CH₃–NH₂',5],['CH₃–CH₂–OH',0],['H–COOH',3]]},
  quiz:[{q:'El vinagre contiene…',o:['Ácido acético','Etanol','Acetona'],a:0,e:'Ácido etanoico, –COOH.'},
   {q:'Ácido carboxílico + alcohol produce…',o:['Éster + agua','Amina','Aldehído'],a:0,e:'Esterificación.'},
   {q:'Las aminas contienen…',o:['Azufre','Nitrógeno','Cloro'],a:1,e:'Derivan del amoníaco.'}]}
]},
{id:'g11u4',title:'Química de la vida y de la industria',desc:'Biomoléculas, polímeros y combustibles.',lessons:[
 {id:'g11u4l1',title:'Biomoléculas',time:50,std:'Explico algunos cambios químicos que ocurren en el ser humano.',dba:'',
  body:['Los seres vivos están hechos de cuatro tipos de biomoléculas orgánicas: <b>carbohidratos</b> (energía: glucosa, almidón), <b>lípidos</b> (reserva de energía y membranas: aceites, grasas), <b>proteínas</b> (estructura y enzimas, formadas por aminoácidos) y <b>ácidos nucleicos</b> (ADN y ARN, la información genética).'],
  key:'Carbohidratos: energía rápida. Lípidos: reserva. Proteínas: estructura y enzimas. Ácidos nucleicos: información.',
  co:'La papa, el arroz y la yuca aportan almidón; el fríjol, proteína; el aguacate, lípidos.',
  act:{type:'classify',prompt:'¿A qué grupo pertenece cada biomolécula o alimento principal?',bins:['Carbohidrato','Lípido','Proteína','Ácido nucleico'],items:[['Almidón de la yuca',0],['Aceite de palma',1],['Queratina del cabello',2],['ADN',3],['Glucosa',0],['Enzima amilasa de la saliva',2],['Grasa del aguacate',1],['ARN',3]]},
  quiz:[{q:'Las proteínas están formadas por…',o:['Glucosa','Aminoácidos','Ácidos grasos'],a:1,e:'Cadenas de aminoácidos.'},
   {q:'La principal reserva de energía a largo plazo son…',o:['Los lípidos','Los ácidos nucleicos','Las vitaminas'],a:0,e:'Aportan unas 9 kcal por gramo.'},
   {q:'Las enzimas son…',o:['Carbohidratos','Proteínas que actúan como catalizadores','Lípidos'],a:1,e:'Aceleran las reacciones del cuerpo.'}]},
 {id:'g11u4l2',title:'Polímeros y plásticos',time:50,std:'Explica cambios químicos en la cocina, la industria y el ambiente.',dba:'DBA 11°: analiza cuestiones ambientales actuales desde una visión sistémica.',
  body:['Un <b>polímero</b> es una molécula gigante formada por muchas unidades repetidas (<b>monómeros</b>). El polietileno de las bolsas se forma uniendo miles de moléculas de eteno.',
   'Hay polímeros <b>naturales</b> (almidón, celulosa, caucho, proteínas) y <b>sintéticos</b> (PET, PVC, nailon, icopor).',
   'Muchos plásticos tardan cientos de años en degradarse. Reciclar requiere separarlos por tipo; el número dentro del triángulo lo indica.'],
  key:'Polímero = muchas unidades repetidas.',
  co:'Colombia regula desde 2022 la eliminación gradual de plásticos de un solo uso (Ley 2232 de 2022).',
  act:{type:'classify',prompt:'¿Polímero natural o sintético?',bins:['Natural','Sintético'],items:[['Celulosa del papel',0],['Botella PET',1],['Caucho natural',0],['Tubería de PVC',1],['Almidón',0],['Nailon de las medias',1],['Seda',0],['Icopor (poliestireno)',1]]},
  quiz:[{q:'El monómero del polietileno es…',o:['Metano','Eteno','Benceno'],a:1,e:'El doble enlace se abre para unir cadenas.'},
   {q:'¿Cuál es un polímero natural?',o:['PVC','Celulosa','PET'],a:1,e:'Forma la madera y el papel.'},
   {q:'¿Por qué es difícil reciclar plásticos mezclados?',o:['Porque cada tipo de polímero se procesa diferente','Porque pesan mucho','Porque son naturales'],a:0,e:'Hay que separarlos por código.'}]},
 {id:'g11u4l3',title:'Combustibles y energía',time:55,std:'Explica cambios químicos en la cocina, la industria y el ambiente.',dba:'DBA 11°: analiza cuestiones ambientales actuales desde una visión sistémica.',
  body:['La <b>combustión completa</b> de un hidrocarburo con oxígeno produce CO₂, agua y energía. Si falta oxígeno se produce monóxido de carbono (CO), un gas muy tóxico.',
   'El petróleo se separa por <b>destilación fraccionada</b> en gases, gasolina, queroseno, diésel y asfaltos, según su punto de ebullición.',
   'Los biocombustibles como el etanol y el biodiésel de palma reducen parte de las emisiones netas.'],
  key:'Hidrocarburo + O₂ → CO₂ + H₂O + energía.',
  co:'Colombia refina petróleo en Barrancabermeja y Cartagena, y mezcla biodiésel de palma en el diésel.',
  act:{type:'balance',prompt:'Balancea la combustión de cada combustible.',rx:[{name:'Propano (cilindro)',r:['C3H8','O2'],p:['CO2','H2O'],c:[1,5,3,4]},{name:'Butano (encendedor)',r:['C4H10','O2'],p:['CO2','H2O'],c:[2,13,8,10],hints:['Carbono: 4 CO₂. Hidrógeno: 5 H₂O.','Oxígeno: 8 + 5 = 13 átomos; con O₂ quedaría 6,5.','Multiplica todo por 2: 2 C₄H₁₀ + 13 O₂ → 8 CO₂ + 10 H₂O.']},{name:'Etanol (biocombustible)',r:['C2H5OH','O2'],p:['CO2','H2O'],c:[1,3,2,3]}]},
  quiz:[{q:'La combustión incompleta produce…',o:['Solo agua','Monóxido de carbono','Oxígeno'],a:1,e:'Por eso los calentadores a gas necesitan ventilación.'},
   {q:'La destilación fraccionada separa el petróleo por…',o:['Color','Punto de ebullición','Densidad únicamente'],a:1,e:'Cada fracción se condensa a distinta altura de la torre.'},
   {q:'C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O. ¿Cuántos moles de CO₂ salen de 2 mol de propano?',o:['3','6','5'],a:1,e:'1 : 3, entonces 6.'}]}
]}
]};
export default grade;
