// Contenido del grado 6° (Estándares MEN 2004, DBA 2016)
import type { Grade } from './types';
const grade: Grade = 
{id:'g6',n:6,title:'La materia y sus cambios',desc:'Qué es la materia, cómo se mide, cómo se mezcla y cómo cambia.',units:[
{id:'g6u1',title:'La materia',desc:'Masa, volumen, densidad y estados de agregación.',lessons:[
 {id:'g6u1l1',title:'¿Qué es la materia?',time:50,std:'Clasifico y verifico las propiedades de la materia.',dba:'DBA 6°: la clasificación de los materiales a partir de grupos de sustancias.',
  body:['Materia es todo lo que tiene <b>masa</b> y ocupa un lugar en el espacio, es decir, tiene <b>volumen</b>. El agua, el aire que respiras, una piedra y tu propio cuerpo son materia.',
   'Hay cosas que percibimos pero no son materia: la luz, el sonido y el calor son formas de <b>energía</b>. No tienen masa ni ocupan espacio por sí mismas.',
   'La masa se mide con una balanza, en gramos (g) o kilogramos (kg). El volumen se mide en mililitros (mL) o centímetros cúbicos (cm³); 1 mL es lo mismo que 1 cm³.'],
  key:'Si tiene masa y ocupa espacio, es materia. Si no, probablemente es energía.',
  co:'Aunque no lo veas, el aire es materia: un balón de fútbol inflado pesa unos gramos más que desinflado.',
  act:{type:'classify',prompt:'Clasifica cada ejemplo como materia o energía.',bins:['Materia','Energía'],items:[['El aire dentro de una llanta',0],['La luz del sol',1],['Una arepa',0],['El sonido de un tambor',1],['El vapor de la olla',0],['El calor de la estufa',1],['El agua del río Magdalena',0],['La electricidad de un enchufe',1]]},
  quiz:[{q:'¿Cuál de estas NO es materia?',o:['El aire','El agua','La luz','El hielo'],a:2,e:'La luz es energía: no tiene masa ni ocupa espacio.'},
   {q:'¿Qué instrumento mide la masa?',o:['La probeta','La balanza','El termómetro','La regla'],a:1,e:'La balanza mide masa; la probeta mide volumen de líquidos.'},
   {q:'1 mL equivale a…',o:['1 cm³','1 g siempre','1 L','10 cm³'],a:0,e:'1 mL = 1 cm³. Solo en el agua 1 mL pesa aproximadamente 1 g.'}],
  tip:'Lleve un globo desinflado y otro inflado a una balanza de cocina para mostrar que el aire tiene masa.'},
 {id:'g6u1l2',title:'Propiedades de la materia y densidad',time:55,std:'Clasifico y verifico las propiedades de la materia.',dba:'DBA 6°: la temperatura y la presión influyen en las propiedades fisicoquímicas de las sustancias.',
  body:['Las <b>propiedades generales</b> las tiene toda la materia: masa, volumen, peso. No sirven para distinguir una sustancia de otra.',
   'Las <b>propiedades específicas</b> sí identifican una sustancia: color, olor, punto de fusión, punto de ebullición y <b>densidad</b>.',
   'La densidad dice cuánta masa hay en cada unidad de volumen: <b>d = m ÷ V</b>. Si un objeto es menos denso que el agua (1 g/cm³), flota; si es más denso, se hunde. No importa qué tan grande sea el objeto: un tronco enorme flota y un clavo pequeño se hunde.'],
  key:'La densidad no depende del tamaño del objeto, depende del material.',
  co:'Los troncos de balso que usaban los pueblos del Pacífico para balsas tienen una densidad cercana a 0,15 g/cm³.',
  act:{type:'density',prompt:'Elige un material y cambia el tamaño del bloque. Observa si la densidad cambia.',ask:[{q:'¿Cuál es la densidad del aluminio?',a:2.7,tol:.05,unit:'g/cm³'},{q:'Si haces más grande el bloque de madera, su densidad…',o:['Aumenta','Disminuye','Sigue igual'],a:2,e:'La masa y el volumen crecen juntos: el cociente no cambia.'},{q:'¿Qué masa tiene un bloque de hierro de 10 cm³?',a:78.7,tol:1,unit:'g',h:'m = d × V = 7,87 × 10.'}]},
  quiz:[{q:'¿Cuál es una propiedad específica?',o:['Masa','Volumen','Densidad','Peso'],a:2,e:'La densidad es característica de cada sustancia.'},
   {q:'Un objeto de 20 g ocupa 40 cm³. Su densidad es…',o:['0,5 g/cm³','2 g/cm³','800 g/cm³','60 g/cm³'],a:0,e:'d = 20 ÷ 40 = 0,5 g/cm³. Flotaría en agua.'},
   {q:'¿Por qué un barco de hierro flota?',o:['El hierro es menos denso que el agua','Su forma encierra mucho aire, y la densidad promedio del barco es menor que la del agua','Porque el mar es salado','Porque es grande'],a:1,e:'El casco hueco contiene aire: la densidad promedio del barco es menor que 1 g/cm³.'}]},
 {id:'g6u1l3',title:'Estados de la materia',time:55,std:'Explico la formación de moléculas y los estados de la materia a partir de fuerzas electrostáticas.',dba:'DBA 6°: la temperatura y la presión influyen en las propiedades fisicoquímicas de las sustancias.',
  body:['La materia se presenta en tres estados comunes. En el <b>sólido</b> las partículas están muy juntas y solo vibran. En el <b>líquido</b> están juntas pero se deslizan. En el <b>gas</b> están separadas y se mueven rápido en todas direcciones.',
   'Al calentar, las partículas se mueven más rápido y pueden cambiar de estado: <b>fusión</b> (sólido a líquido), <b>vaporización</b> (líquido a gas). Al enfriar ocurren la <b>condensación</b> y la <b>solidificación</b>.',
   'El punto de ebullición depende de la presión atmosférica. A menor presión, el agua hierve a menor temperatura.'],
  key:'Calentar da energía a las partículas: se mueven más y se separan.',
  co:'En Bogotá el agua hierve a unos 92 °C, no a 100 °C, porque a 2.600 m de altura hay menos presión. Por eso los fríjoles se demoran más en cocinarse allá.',
  act:{type:'states',prompt:'Mueve la temperatura y cambia de ciudad. Observa cómo se mueven las partículas.',ask:[{q:'¿A qué temperatura hierve el agua en Bogotá según el simulador?',a:92,tol:.5,unit:'°C'},{q:'A 95 °C, en Bogotá el agua está…',o:['Sólida','Líquida','Gaseosa'],a:2,e:'95 °C supera los 92 °C de ebullición en Bogotá.'},{q:'A 95 °C, en Cartagena el agua está…',o:['Sólida','Líquida','Gaseosa'],a:1,e:'A nivel del mar el agua necesita 100 °C para hervir.'}]},
  quiz:[{q:'¿En qué estado las partículas solo vibran en su lugar?',o:['Sólido','Líquido','Gaseoso'],a:0,e:'En el sólido las fuerzas entre partículas las mantienen fijas.'},
   {q:'El paso de gas a líquido se llama…',o:['Fusión','Condensación','Sublimación','Evaporación'],a:1,e:'Condensación: como el vapor que se vuelve gotas en la tapa de la olla.'},
   {q:'¿Por qué el agua hierve a menor temperatura en Bogotá que en Cartagena?',o:['Porque hace más frío','Porque la presión atmosférica es menor','Porque el agua es diferente','Porque hay menos oxígeno en el agua'],a:1,e:'Con menos presión encima, las moléculas escapan al estado gaseoso con menos energía.'}],
  tip:'Pregunte por qué la olla a presión cocina más rápido: conecta presión y punto de ebullición.'}
]},
{id:'g6u2',title:'Sustancias y mezclas',desc:'Elementos, compuestos, mezclas y cómo separarlas.',lessons:[
 {id:'g6u2l1',title:'Sustancias puras: elementos y compuestos',time:50,std:'Clasifico materiales en sustancias puras o mezclas.',dba:'DBA 6°: la clasificación de los materiales a partir de grupos de sustancias.',
  body:['Una <b>sustancia pura</b> tiene composición fija. Hay dos tipos.',
   'Un <b>elemento</b> está formado por un solo tipo de átomo: oxígeno (O), hierro (Fe), oro (Au). Están en la tabla periódica.',
   'Un <b>compuesto</b> tiene dos o más elementos unidos químicamente en proporción fija: agua (H₂O), sal (NaCl), dióxido de carbono (CO₂). Sus propiedades son distintas a las de sus elementos: el sodio explota en agua y el cloro es venenoso, pero juntos forman la sal de cocina.'],
  key:'Elemento: un tipo de átomo. Compuesto: varios elementos unidos en proporción fija.',
  co:'Colombia produce oro (elemento) en Antioquia y Chocó, y sal (compuesto) en Zipaquirá y Manaure.',
  act:{type:'classify',prompt:'Clasifica cada sustancia.',bins:['Elemento','Compuesto','Mezcla'],items:[['Oro (Au)',0],['Agua (H₂O)',1],['Aire',2],['Hierro (Fe)',0],['Sal (NaCl)',1],['Agua de panela',2],['Oxígeno (O₂)',0],['Azúcar (C₁₂H₂₂O₁₁)',1],['Tinto (café)',2]]},
  quiz:[{q:'El agua (H₂O) es…',o:['Un elemento','Un compuesto','Una mezcla'],a:1,e:'Hidrógeno y oxígeno unidos químicamente en proporción fija 2:1.'},
   {q:'¿Cuál es un elemento?',o:['CO₂','NaCl','Cu','H₂O'],a:2,e:'Cu es cobre: un solo tipo de átomo.'},
   {q:'¿Por qué el O₂ es un elemento y no un compuesto?',o:['Porque es un gas','Porque tiene un solo tipo de átomo, aunque sean dos átomos','Porque lo respiramos','Porque no tiene color'],a:1,e:'Dos átomos de oxígeno siguen siendo un solo elemento.'}]},
 {id:'g6u2l2',title:'Mezclas homogéneas y heterogéneas',time:50,std:'Clasifico materiales en sustancias puras o mezclas.',dba:'DBA 6°: la clasificación de los materiales a partir de grupos de sustancias.',
  body:['Una <b>mezcla</b> une dos o más sustancias sin que cambien químicamente. Cada una conserva sus propiedades y la proporción puede variar.',
   'En una mezcla <b>homogénea</b> no se distinguen los componentes a simple vista: agua con azúcar, aire, gaseosa sin burbujas. También se llaman soluciones.',
   'En una mezcla <b>heterogénea</b> sí se ven las partes: arroz con fríjoles, agua con aceite, arena con piedras.'],
  key:'Si a simple vista se ve una sola fase, es homogénea. Si se ven varias, es heterogénea.',
  co:'El sancocho es una mezcla heterogénea; el agua de panela bien disuelta es homogénea.',
  act:{type:'classify',prompt:'¿Homogénea o heterogénea?',bins:['Homogénea','Heterogénea'],items:[['Agua de panela',0],['Ensalada de frutas',1],['Aire limpio',0],['Agua con aceite',1],['Gaseosa sin burbujas',0],['Arena y piedras',1],['Vinagre',0],['Sancocho',1]]},
  quiz:[{q:'¿Cuál es una mezcla homogénea?',o:['Agua con arena','Agua con sal disuelta','Arroz con pollo','Granito'],a:1,e:'La sal disuelta no se distingue: una sola fase.'},
   {q:'En una mezcla, las sustancias…',o:['Cambian químicamente','Conservan sus propiedades','Forman un compuesto nuevo','Siempre están en la misma proporción'],a:1,e:'Por eso se pueden separar por métodos físicos.'},
   {q:'El agua con aceite es heterogénea porque…',o:['Se ven dos capas','Es líquida','Tiene color','Se puede beber'],a:0,e:'Se distinguen dos fases: el aceite queda encima.'}]},
 {id:'g6u2l3',title:'Métodos de separación de mezclas',time:55,std:'Verifico diferentes métodos de separación de mezclas.',dba:'',
  body:['Como las sustancias de una mezcla conservan sus propiedades, podemos separarlas aprovechando esas diferencias.',
   '<b>Filtración</b>: separa un sólido que no se disuelve de un líquido (café y agua). <b>Decantación</b>: separa líquidos que no se mezclan o un sólido que se asienta (agua y aceite). <b>Evaporación</b>: separa un sólido disuelto al evaporar el líquido (sal del agua de mar). <b>Destilación</b>: separa líquidos con distinto punto de ebullición (alcohol y agua). <b>Imantación</b>: separa metales como el hierro.'],
  key:'Cada método aprovecha una diferencia: tamaño, densidad, punto de ebullición o magnetismo.',
  co:'En Manaure (La Guajira) se obtiene sal por evaporación del agua de mar en grandes charcas al sol.',
  act:{type:'classify',prompt:'Elige el mejor método para separar cada mezcla.',bins:['Filtración','Decantación','Evaporación','Destilación','Imantación'],items:[['Café molido y agua',0],['Agua y aceite',1],['Sal y agua de mar',2],['Alcohol y agua',3],['Limaduras de hierro y arena',4],['Arena y agua',0]]},
  quiz:[{q:'Para obtener sal del agua de mar se usa…',o:['Filtración','Evaporación','Imantación','Tamizado'],a:1,e:'El agua se evapora y la sal queda.'},
   {q:'La destilación se basa en diferencias de…',o:['Color','Punto de ebullición','Magnetismo','Tamaño'],a:1,e:'El líquido que hierve primero se evapora y se recoge al condensarse.'},
   {q:'El colador de la cocina hace una…',o:['Filtración o tamizado','Destilación','Evaporación','Imantación'],a:0,e:'Deja pasar el líquido y retiene el sólido.'}],
  tip:'Práctica casera: separar arena, sal y limaduras en tres pasos (imán, filtrar, evaporar).'}
]},
{id:'g6u3',title:'Cambios de la materia',desc:'Diferencia entre cambios físicos y químicos en la vida diaria.',lessons:[
 {id:'g6u3l1',title:'Cambio físico y cambio químico',time:50,std:'Verifico que la cocción de alimentos genera cambios físicos y químicos.',dba:'',
  body:['En un <b>cambio físico</b> la sustancia sigue siendo la misma: cambia su forma o su estado. Derretir hielo, romper un papel o disolver azúcar son cambios físicos.',
   'En un <b>cambio químico</b> se forman sustancias nuevas. Hay pistas: cambio de color, liberación de gas, luz o calor, olor nuevo o formación de un sólido.',
   'Quemar papel, oxidarse un clavo o fermentarse la fruta son cambios químicos: no se pueden revertir fácilmente.'],
  key:'Si aparece una sustancia nueva, el cambio es químico.',
  co:'La fermentación del maíz para hacer chicha es un cambio químico: los azúcares se transforman en alcohol y gas.',
  act:{type:'classify',prompt:'¿Cambio físico o químico?',bins:['Físico','Químico'],items:[['Derretir chocolate',0],['Tostar pan',1],['Oxidación de una reja',1],['Romper un vaso',0],['Hervir agua',0],['Quemar leña',1],['Madurar un banano',1],['Disolver sal en agua',0]]},
  quiz:[{q:'¿Cuál es un cambio químico?',o:['Congelar agua','Cortar madera','Freír un huevo','Doblar una hoja'],a:2,e:'La clara cambia de color y textura: se forman sustancias nuevas.'},
   {q:'¿Qué pista indica un cambio químico?',o:['Cambio de forma','Liberación de gas con olor nuevo','Cambio de tamaño','Cambio de lugar'],a:1,e:'Un gas nuevo indica que se formaron otras sustancias.'},
   {q:'Evaporar agua es un cambio…',o:['Químico, porque desaparece','Físico, porque sigue siendo agua','Nuclear','Biológico'],a:1,e:'El vapor sigue siendo H₂O.'}]},
 {id:'g6u3l2',title:'La química en la cocina',time:45,std:'Verifico que la cocción de alimentos genera cambios físicos y químicos.',dba:'',
  body:['La cocina es un laboratorio. Cuando la arepa se dora en el budare, los azúcares y proteínas reaccionan y producen color y sabor nuevos (reacción de Maillard).',
   'El bicarbonato con vinagre o limón produce dióxido de carbono: por eso se usa para que las masas crezcan.',
   'Otros procesos son físicos: picar cebolla, derretir mantequilla o disolver panela.'],
  key:'Dorar, fermentar y leudar son cambios químicos; picar, derretir y disolver son físicos.',
  co:'El pandebono y el buñuelo se inflan por el gas que se expande con el calor y por las reacciones de la masa al hornearse o freírse.',
  act:{type:'classify',prompt:'Clasifica lo que pasa en la cocina.',bins:['Físico','Químico'],items:[['Dorar la arepa en el budare',1],['Picar cebolla',0],['Bicarbonato con limón que burbujea',1],['Derretir mantequilla',0],['Leche que se corta',1],['Disolver panela',0]]},
  quiz:[{q:'Al mezclar bicarbonato y vinagre se libera…',o:['Oxígeno','Dióxido de carbono','Hidrógeno','Nitrógeno'],a:1,e:'Las burbujas son CO₂: un gas nuevo, cambio químico.'},
   {q:'Dorar un alimento es un cambio químico porque…',o:['Cambia de temperatura','Se forman sustancias nuevas de color y sabor','Pierde agua','Se ablanda'],a:1,e:'Es la reacción de Maillard entre azúcares y proteínas.'},
   {q:'Disolver azúcar en el tinto es un cambio…',o:['Físico','Químico'],a:0,e:'El azúcar sigue siendo azúcar; se puede recuperar evaporando.'}],
  tip:'Actividad de cierre: cada estudiante trae un ejemplo de su casa y lo clasifica frente al grupo.'}
]}
]};
export default grade;
