// Contenido del grado 7° (Estándares MEN 2004, DBA 2016)
import type { Grade } from './types';
const grade: Grade = 
{id:'g7',n:7,title:'Átomos, elementos y tabla periódica',desc:'De qué están hechas las cosas y cómo se organizan los elementos.',units:[
{id:'g7u1',title:'El átomo',desc:'Cómo cambió la idea de átomo y qué partículas lo forman.',lessons:[
 {id:'g7u1l1',title:'Historia de los modelos atómicos',time:55,std:'Explico cómo un número limitado de elementos hace posible la diversidad de la materia conocida.',dba:'DBA 7°: las sustancias se forman a partir de la interacción de los elementos.',
  body:['La idea de átomo cambió con los experimentos. <b>Dalton</b> (1808) propuso esferas macizas e indivisibles. <b>Thomson</b> (1897) descubrió el electrón y propuso un “pudín con pasas”.',
   '<b>Rutherford</b> (1911) disparó partículas alfa contra una lámina de oro: casi todas pasaron, pero unas pocas rebotaron. Concluyó que el átomo es casi vacío, con un <b>núcleo</b> pequeño y positivo.',
   '<b>Bohr</b> (1913) ubicó a los electrones en <b>niveles de energía</b>. El modelo actual, el <b>mecánico-cuántico</b>, describe regiones de probabilidad llamadas orbitales.'],
  key:'Cada modelo corrigió al anterior gracias a un experimento nuevo. Así avanza la ciencia.',
  co:'El Servicio Geológico Colombiano opera el único reactor nuclear de investigación del país, en Bogotá, que se usa para producir material para análisis y estudios.',
  act:{type:'order',prompt:'Ordena los modelos atómicos del más antiguo al más reciente.',items:['Dalton: esferas macizas indivisibles','Thomson: electrones incrustados en una masa positiva','Rutherford: núcleo pequeño y positivo, mucho vacío','Bohr: electrones en niveles de energía','Mecánico-cuántico: orbitales de probabilidad']},
  quiz:[{q:'¿Qué descubrió el experimento de Rutherford?',o:['El electrón','Que el átomo tiene un núcleo pequeño y denso','Los orbitales','Que el átomo es indivisible'],a:1,e:'Las partículas que rebotaban mostraron un núcleo concentrado.'},
   {q:'¿Quién propuso niveles de energía para los electrones?',o:['Dalton','Thomson','Bohr','Demócrito'],a:2,e:'Bohr explicó así los colores de luz que emite el hidrógeno.'},
   {q:'¿Por qué se reemplazó el modelo de Thomson?',o:['Porque era muy antiguo','Porque un experimento mostró resultados que no podía explicar','Porque Thomson se equivocó al medir','Por votación'],a:1,e:'La lámina de oro de Rutherford no encajaba con el pudín con pasas.'}],
  tip:'Dramatice el experimento de Rutherford lanzando bolitas de papel a una caja con un objeto pequeño escondido.'},
 {id:'g7u1l2',title:'Protones, neutrones y electrones',time:55,std:'Explico el desarrollo de modelos de organización de los elementos químicos.',dba:'DBA 7°: las sustancias se forman a partir de la interacción de los elementos.',
  body:['El núcleo tiene <b>protones</b> (carga +) y <b>neutrones</b> (sin carga). Alrededor están los <b>electrones</b> (carga −), mucho más livianos.',
   'El <b>número atómico (Z)</b> es el número de protones y define el elemento: todo átomo con 6 protones es carbono. El <b>número de masa (A)</b> es protones + neutrones.',
   'En un átomo neutro hay tantos electrones como protones. Si gana o pierde electrones se vuelve un <b>ion</b>. Si cambian los neutrones, es otro <b>isótopo</b> del mismo elemento.'],
  key:'Protones: qué elemento es. Neutrones: qué isótopo. Electrones: qué carga tiene.',
  co:'El carbono-14 permite fechar restos arqueológicos, como los hallazgos de la Serranía de Chiribiquete.',
  act:{type:'atom',prompt:'Arma cada átomo agregando o quitando partículas.',start:{p:1,n:0,e:0},targets:[{p:2,n:2,e:2,label:'Helio-4 neutro'},{p:6,n:6,e:6,label:'Carbono-12 neutro'},{p:8,n:8,e:8,label:'Oxígeno-16 neutro'}]},
  quiz:[{q:'Un átomo tiene 11 protones y 12 neutrones. ¿Cuál es su número de masa?',o:['11','12','23','1'],a:2,e:'A = 11 + 12 = 23. Es el sodio-23.'},
   {q:'¿Qué partícula define qué elemento es un átomo?',o:['El electrón','El neutrón','El protón','El fotón'],a:2,e:'El número de protones es el número atómico.'},
   {q:'Un átomo neutro de oxígeno (Z = 8) tiene…',o:['8 electrones','16 electrones','0 electrones','6 electrones'],a:0,e:'Neutro significa igual número de protones y electrones.'}]}
]},
{id:'g7u2',title:'La tabla periódica',desc:'Cómo se organizan los elementos y qué nos dice su ubicación.',lessons:[
 {id:'g7u2l1',title:'Grupos y periodos',time:50,std:'Explico y utilizo la tabla periódica como herramienta para predecir procesos químicos.',dba:'DBA 7°: las sustancias se forman a partir de la interacción de los elementos.',
  body:['Mendeléyev ordenó los elementos en 1869 y dejó huecos para elementos que aún no se conocían. Hoy se ordenan por <b>número atómico</b>.',
   'Las filas se llaman <b>periodos</b>: indican cuántos niveles de energía tienen los electrones. Las columnas se llaman <b>grupos</b>: los elementos de un grupo tienen propiedades parecidas porque tienen los mismos electrones externos.',
   'Algunas familias: <b>metales alcalinos</b> (grupo 1), <b>halógenos</b> (grupo 17) y <b>gases nobles</b> (grupo 18), que casi no reaccionan.'],
  key:'Mismo grupo, propiedades parecidas. Mismo periodo, mismo número de niveles.',
  co:'El níquel de Cerro Matoso (Córdoba) está en el periodo 4, grupo 10, junto al hierro y el cobalto.',
  act:{type:'ptable',prompt:'Toca los elementos para ver su ficha y cumple los retos.',find:[{q:'Un gas noble del periodo 2',a:'Ne'},{q:'Un metal alcalino del periodo 3',a:'Na'},{q:'El halógeno del periodo 3',a:'Cl'},{q:'El elemento del periodo 4, grupo 10',a:'Ni'}]},
  quiz:[{q:'Los elementos de un mismo grupo…',o:['Tienen la misma masa','Tienen propiedades químicas parecidas','Son todos gases','Tienen el mismo número de protones'],a:1,e:'Comparten el número de electrones de valencia.'},
   {q:'El periodo de un elemento indica…',o:['Sus electrones de valencia','Sus niveles de energía ocupados','Su carga','Su densidad'],a:1,e:'Periodo 3 = electrones en 3 niveles.'},
   {q:'¿Por qué los gases nobles casi no reaccionan?',o:['Porque son gases','Porque tienen su capa externa completa','Porque son muy pesados','Porque son raros'],a:1,e:'Ya tienen 8 electrones externos (el helio, 2).'}]},
 {id:'g7u2l2',title:'Metales, no metales y metaloides',time:50,std:'Explico y utilizo la tabla periódica como herramienta para predecir procesos químicos.',dba:'',
  body:['Los <b>metales</b> (a la izquierda y el centro) brillan, conducen calor y electricidad, se pueden estirar en hilos y tienden a perder electrones.',
   'Los <b>no metales</b> (arriba a la derecha) no brillan, conducen mal y tienden a ganar electrones. Muchos son gases a temperatura ambiente, como el oxígeno y el nitrógeno.',
   'Los <b>metaloides</b> (en la “escalera”) tienen propiedades intermedias. El silicio es la base de los chips y paneles solares.'],
  key:'Metales pierden electrones; no metales los ganan.',
  co:'Colombia exporta carbón (no metal), ferroníquel y oro (metales). El cobre de los cables también es un metal.',
  act:{type:'classify',prompt:'Clasifica cada elemento.',bins:['Metal','No metal','Metaloide'],items:[['Hierro (Fe)',0],['Oxígeno (O)',1],['Silicio (Si)',2],['Cobre (Cu)',0],['Azufre (S)',1],['Sodio (Na)',0],['Boro (B)',2],['Cloro (Cl)',1],['Oro (Au)',0]]},
  quiz:[{q:'¿Cuál es buen conductor de electricidad?',o:['Azufre','Cobre','Oxígeno','Carbono (diamante)'],a:1,e:'Por eso los cables son de cobre.'},
   {q:'Los no metales tienden a…',o:['Perder electrones','Ganar electrones','No tener electrones','Brillar'],a:1,e:'Así completan su capa externa.'},
   {q:'El silicio es…',o:['Un metal alcalino','Un gas noble','Un metaloide','Un halógeno'],a:2,e:'Semiconductor: base de la electrónica.'}]},
 {id:'g7u2l3',title:'Propiedades periódicas',time:55,std:'Uso la tabla periódica para determinar propiedades físicas y químicas de los elementos.',dba:'',
  body:['Algunas propiedades cambian de forma ordenada en la tabla. Por eso se llaman <b>periódicas</b>.',
   'El <b>radio atómico</b> aumenta hacia abajo (más niveles) y disminuye hacia la derecha (el núcleo atrae más fuerte).',
   'La <b>electronegatividad</b>, la fuerza con que un átomo atrae electrones en un enlace, aumenta hacia la derecha y hacia arriba. El flúor es el más electronegativo.'],
  key:'Abajo e izquierda: átomos grandes. Arriba y derecha: átomos muy electronegativos.',
  co:'',
  act:{type:'ptable',prompt:'Cambia entre “Radio atómico” y “Electronegatividad” y encuentra los extremos.',find:[{q:'El átomo más grande de la tabla (hasta Z = 36)',a:'K'},{q:'El elemento más electronegativo',a:'F'},{q:'El átomo más pequeño del periodo 3',a:'Ar'}]},
  quiz:[{q:'En un periodo, de izquierda a derecha, el radio atómico…',o:['Aumenta','Disminuye','No cambia'],a:1,e:'Más protones jalan a los electrones hacia el núcleo.'},
   {q:'¿Cuál es más electronegativo?',o:['Sodio','Cloro','Potasio','Calcio'],a:1,e:'El cloro está arriba a la derecha.'},
   {q:'Bajando en un grupo, el radio…',o:['Aumenta, porque hay más niveles','Disminuye','Es igual'],a:0,e:'Cada periodo agrega un nivel de energía.'}]}
]},
{id:'g7u3',title:'Moléculas y compuestos',desc:'Cómo los elementos se combinan y cómo se representan.',lessons:[
 {id:'g7u3l1',title:'Moléculas y fórmulas químicas',time:50,std:'Explico la formación de moléculas y los estados de la materia a partir de fuerzas electrostáticas.',dba:'DBA 7°: las sustancias se forman a partir de la interacción de los elementos.',
  body:['Una <b>molécula</b> es un grupo de átomos unidos. La <b>fórmula química</b> dice qué átomos tiene y cuántos: en H₂O hay 2 hidrógenos y 1 oxígeno.',
   'El subíndice indica cuántos átomos de ese elemento hay. Si no hay número, es 1.',
   'Con pocos elementos se forman millones de sustancias: el carbono, el hidrógeno y el oxígeno forman el azúcar, el alcohol y el vinagre.'],
  key:'La fórmula es como una receta: dice los ingredientes (elementos) y las cantidades (subíndices).',
  co:'El CO₂ que exhalas y el CH₄ del gas natural tienen solo dos elementos cada uno.',
  act:{type:'mol3d',prompt:'Gira cada molécula y cuenta sus átomos. Compara con la fórmula.',mols:['H2O','CO2','NH3','CH4']},
  quiz:[{q:'¿Cuántos átomos tiene una molécula de CH₄?',o:['2','4','5','1'],a:2,e:'1 carbono + 4 hidrógenos = 5 átomos.'},
   {q:'En NH₃, el número 3 indica…',o:['3 nitrógenos','3 hidrógenos','3 moléculas','La carga'],a:1,e:'El subíndice va después del elemento que multiplica.'},
   {q:'¿Cuántos elementos distintos hay en CO₂?',o:['1','2','3'],a:1,e:'Carbono y oxígeno.'}]},
 {id:'g7u3l2',title:'Fuerzas entre partículas',time:45,std:'Explico la formación de moléculas y los estados de la materia a partir de fuerzas electrostáticas.',dba:'',
  body:['Entre las partículas hay fuerzas de atracción eléctrica. Si son fuertes frente al movimiento de las partículas, la sustancia es sólida; si son débiles, es gas.',
   'La temperatura mide qué tan rápido se mueven las partículas. Al calentar, el movimiento vence a las fuerzas de atracción y la sustancia cambia de estado.',
   'El agua tiene fuerzas especialmente fuertes entre moléculas (puentes de hidrógeno). Por eso hierve a una temperatura alta para una molécula tan pequeña.'],
  key:'Estado = competencia entre las fuerzas que unen y el movimiento que separa.',
  co:'',
  act:{type:'states',prompt:'Busca el punto donde el movimiento vence a las fuerzas de atracción.',ask:[{q:'¿A qué temperatura el hielo se funde?',a:0,tol:.5,unit:'°C'},{q:'Al subir la temperatura, las partículas…',o:['Se mueven más lento','Se mueven más rápido','Se detienen'],a:1}]},
  quiz:[{q:'Una sustancia es gaseosa a temperatura ambiente cuando…',o:['Sus fuerzas de atracción son débiles','Sus fuerzas son muy fuertes','No tiene partículas'],a:0,e:'El movimiento gana y las partículas se separan.'},
   {q:'La temperatura está relacionada con…',o:['El color','La velocidad de las partículas','La masa de los átomos'],a:1,e:'Más temperatura, más energía de movimiento.'},
   {q:'Al enfriar un gas lo suficiente…',o:['Se condensa','Se evapora más','Desaparece'],a:0,e:'Las fuerzas de atracción vuelven a juntar las partículas.'}]}
]}
]};
export default grade;
