// Contenido del grado 8° (Estándares MEN 2004, DBA 2016)
import type { Grade } from './types';
const grade: Grade = 
{id:'g8',n:8,title:'Reacciones químicas y gases',desc:'Cómo se reorganizan los átomos y cómo se comportan los gases.',units:[
{id:'g8u1',title:'Reacciones químicas',desc:'Evidencias, ecuaciones y conservación de la masa.',lessons:[
 {id:'g8u1l1',title:'¿Cómo sé que hubo una reacción?',time:45,std:'Verifico las diferencias entre cambios químicos y mezclas.',dba:'DBA 8°: en una reacción química se recombinan los átomos de las moléculas de los reactivos para generar productos nuevos.',
  body:['En una <b>reacción química</b> unas sustancias (<b>reactivos</b>) se transforman en otras (<b>productos</b>).',
   'Evidencias: cambio de color, desprendimiento de gas, formación de un sólido (precipitado), liberación o absorción de calor, emisión de luz.',
   'Ojo: algunas evidencias también aparecen en cambios físicos. Hervir agua produce gas, pero no es una reacción. La clave es si se formó una sustancia nueva.'],
  key:'Reacción química = sustancias nuevas. Las evidencias ayudan, pero hay que pensar qué se formó.',
  co:'El cambio de color de las hojas del café al secarse y la oxidación del cobre en techos antiguos de Bogotá son reacciones químicas.',
  act:{type:'classify',prompt:'¿Hay reacción química o no?',bins:['Sí hay reacción','No hay reacción'],items:[['Una pastilla efervescente en agua',0],['Hielo que se derrite',1],['Un clavo que se oxida',0],['Azúcar disuelta en agua',1],['Un fósforo que se enciende',0],['Agua que hierve',1],['Leche que se agria',0]]},
  quiz:[{q:'En una reacción, las sustancias iniciales se llaman…',o:['Productos','Reactivos','Catalizadores','Soluciones'],a:1,e:'Reactivos → productos.'},
   {q:'¿Cuál NO es evidencia segura de reacción?',o:['Formación de un precipitado','Cambio de estado del agua al hervir','Cambio de color permanente','Olor nuevo'],a:1,e:'Hervir agua produce gas sin formar sustancia nueva.'},
   {q:'La pastilla efervescente produce burbujas de…',o:['Oxígeno','Dióxido de carbono','Vapor de agua','Hidrógeno'],a:1,e:'El bicarbonato reacciona con un ácido y libera CO₂.'}]},
 {id:'g8u1l2',title:'Ecuaciones y conservación de la masa',time:55,std:'Verifico las diferencias entre cambios químicos y mezclas.',dba:'DBA 8°: en una reacción química se recombinan los átomos de las moléculas de los reactivos para generar productos nuevos.',
  body:['Una <b>ecuación química</b> representa la reacción: reactivos a la izquierda, flecha, productos a la derecha. Ejemplo: CH₄ + 2 O₂ → CO₂ + 2 H₂O.',
   '<b>Lavoisier</b> demostró que en una reacción en recipiente cerrado la masa total no cambia. Los átomos no se crean ni se destruyen: solo cambian de pareja.',
   'Por eso la ecuación debe tener el mismo número de átomos de cada elemento a ambos lados. Los números grandes delante de las fórmulas se llaman <b>coeficientes</b>.'],
  key:'En una reacción los átomos se reorganizan: la masa se conserva.',
  co:'El gas natural que llega a las estufas de Bogotá es casi todo metano (CH₄). Al quemarse produce CO₂ y agua.',
  act:{type:'balance',prompt:'Ajusta los coeficientes hasta que cada elemento tenga los mismos átomos a ambos lados. Cada bolita es un átomo.',rx:[{name:'Combustión del metano',r:['CH4','O2'],p:['CO2','H2O'],c:[1,2,1,2],ctx:'El gas de la estufa arde con el oxígeno del aire.',hints:['Carbono: 1 a cada lado. Deja CH₄ y CO₂ con 1.','Hidrógeno: 4 en CH₄. Cada H₂O tiene 2: necesitas 2 H₂O.','Oxígeno: a la derecha hay 2 + 2 = 4. Pon 2 O₂.']}]},
  quiz:[{q:'Si 16 g de metano reaccionan con 64 g de oxígeno, ¿cuánta masa de productos se forma?',o:['16 g','64 g','80 g','48 g'],a:2,e:'Conservación de la masa: 16 + 64 = 80 g.'},
   {q:'En 2 H₂O, el 2 grande es…',o:['Un subíndice','Un coeficiente','Una carga','Un isótopo'],a:1,e:'Indica 2 moléculas de agua.'},
   {q:'¿Por qué hay que balancear una ecuación?',o:['Por estética','Porque los átomos no se crean ni se destruyen','Para que sea más corta','Porque lo pide el ICFES'],a:1,e:'Ley de conservación de la masa.'}]},
 {id:'g8u1l3',title:'Balanceo por tanteo',time:55,std:'Verifico las diferencias entre cambios químicos y mezclas.',dba:'DBA 8°: en una reacción química se recombinan los átomos de las moléculas de los reactivos para generar productos nuevos.',
  body:['El método de <b>tanteo</b> consiste en probar coeficientes con orden: primero los metales, luego los no metales, después el hidrógeno y al final el oxígeno.',
   'Nunca cambies los subíndices: eso cambiaría la sustancia. H₂O es agua; H₂O₂ es agua oxigenada.',
   'Al final revisa que los coeficientes sean los enteros más pequeños posibles.'],
  key:'Solo se cambian coeficientes, nunca subíndices.',
  co:'La síntesis de amoníaco produce la base de los fertilizantes que se usan en los cultivos de flores de la Sabana de Bogotá.',
  act:{type:'balance',prompt:'Balancea las tres reacciones.',rx:[{name:'Formación de agua',r:['H2','O2'],p:['H2O'],c:[2,1,2]},{name:'Síntesis de amoníaco',r:['N2','H2'],p:['NH3'],c:[1,3,2]},{name:'Oxidación del hierro',r:['Fe','O2'],p:['Fe2O3'],c:[4,3,2],hints:['Hierro: 2 en Fe₂O₃. Oxígeno: 3 en Fe₂O₃ y 2 en O₂; el mínimo común es 6.','Pon 2 Fe₂O₃ (6 oxígenos) y 3 O₂.','Ahora hay 4 Fe a la derecha: pon 4 Fe.']}]},
  quiz:[{q:'Al balancear, ¿qué NO se puede modificar?',o:['Los coeficientes','Los subíndices','El orden de los reactivos'],a:1,e:'Cambiar subíndices cambia la sustancia.'},
   {q:'¿Cuál está balanceada?',o:['H₂ + O₂ → H₂O','2 H₂ + O₂ → 2 H₂O','H₂ + 2 O₂ → 2 H₂O'],a:1,e:'4 H y 2 O a cada lado.'},
   {q:'N₂ + 3 H₂ → 2 NH₃. ¿Cuántos átomos de hidrógeno hay a cada lado?',o:['3','6','2','9'],a:1,e:'3 × 2 = 6 a la izquierda; 2 × 3 = 6 a la derecha.'}]}
]},
{id:'g8u2',title:'Los gases',desc:'Modelo cinético y relación entre presión, volumen y temperatura.',lessons:[
 {id:'g8u2l1',title:'Teoría cinética de los gases',time:50,std:'Comparo sólidos, líquidos y gases teniendo en cuenta el movimiento de sus moléculas y las fuerzas electroestáticas.',dba:'DBA 8°: el comportamiento de un gas ideal está determinado por las relaciones entre temperatura, presión, volumen y cantidad de sustancia.',
  body:['Un gas está formado por partículas muy separadas que se mueven en línea recta y chocan contra las paredes del recipiente.',
   'La <b>presión</b> es el efecto de esos choques. Más choques por segundo, o choques más fuertes, significan más presión.',
   'La <b>temperatura</b> mide la energía de movimiento de las partículas. En química se usa la escala Kelvin: K = °C + 273.'],
  key:'Presión = choques contra las paredes. Temperatura = qué tan rápido se mueven.',
  co:'Una bolsa de papas compradas en Cartagena llega inflada a Bogotá: afuera hay menos presión y el gas de adentro empuja.',
  act:{type:'gas',prompt:'Cambia la temperatura y el volumen. Mira los choques contra las paredes y la presión.',ask:[{q:'Con T = 300 K, ¿qué volumen da una presión cercana a 2,46 atm?',a:10,tol:.5,unit:'L',h:'Mueve el volumen hasta que la presión marque 2,46.'},{q:'Si calientas el gas sin cambiar el volumen, los choques…',o:['Disminuyen','Aumentan','No cambian'],a:1}]},
  quiz:[{q:'25 °C en Kelvin son…',o:['25 K','248 K','298 K','273 K'],a:2,e:'25 + 273 = 298 K.'},
   {q:'La presión de un gas se debe a…',o:['El color del gas','Los choques de las partículas contra las paredes','El peso del recipiente'],a:1,e:'Es el modelo cinético.'},
   {q:'Si el recipiente es más pequeño y la temperatura igual, la presión…',o:['Aumenta','Disminuye','No cambia'],a:0,e:'Las partículas chocan más seguido con las paredes.'}]},
 {id:'g8u2l2',title:'Leyes de Boyle, Charles y Gay-Lussac',time:55,std:'Establezco relaciones entre las variables de estado en un sistema termodinámico para predecir cambios físicos y químicos y las expreso matemáticamente.',dba:'DBA 8°: el comportamiento de un gas ideal está determinado por las relaciones entre temperatura, presión, volumen y cantidad de sustancia.',
  body:['<b>Boyle</b>: a temperatura constante, si el volumen se reduce a la mitad, la presión se duplica. P × V = constante.',
   '<b>Charles</b>: a presión constante, el volumen aumenta con la temperatura. V ÷ T = constante (T en Kelvin).',
   '<b>Gay-Lussac</b>: a volumen constante, la presión aumenta con la temperatura. P ÷ T = constante.'],
  key:'P y V son inversos; V y T, y P y T, son directos.',
  co:'Por la ley de Gay-Lussac no se deben dejar aerosoles dentro de un carro al sol en Cúcuta o Neiva: la presión aumenta con el calor.',
  act:{type:'gas',prompt:'Comprueba las leyes con el simulador.',ask:[{q:'Con T = 300 K y V = 5 L, ¿cuál es la presión?',a:4.92,tol:.05,unit:'atm'},{q:'Ahora duplica el volumen a 10 L (misma T). ¿Qué presión marca?',a:2.46,tol:.05,unit:'atm',e:'La mitad: ley de Boyle.'},{q:'Con V = 10 L, pasa de 300 K a 600 K. La presión…',o:['Se duplica','Se reduce a la mitad','No cambia'],a:0,e:'Ley de Gay-Lussac.'}]},
  quiz:[{q:'Un gas ocupa 4 L a 1 atm. A temperatura constante, ¿qué volumen ocupa a 2 atm?',o:['8 L','2 L','4 L','1 L'],a:1,e:'P₁V₁ = P₂V₂: 1 × 4 = 2 × V₂ → V₂ = 2 L.'},
   {q:'¿Por qué un globo se encoge en la nevera?',o:['Pierde gas','Al bajar la temperatura baja el volumen (Charles)','La nevera tiene más presión'],a:1,e:'V y T son directamente proporcionales.'},
   {q:'En las leyes de los gases la temperatura se usa en…',o:['°C','°F','K'],a:2,e:'Siempre en Kelvin, porque 0 K es el cero real de movimiento.'}]},
 {id:'g8u2l3',title:'La ecuación del gas ideal',time:55,std:'Comparo los modelos que explican el comportamiento de gases ideales y reales.',dba:'DBA 8°: el comportamiento de un gas ideal está determinado por las relaciones entre temperatura, presión, volumen y cantidad de sustancia.',
  body:['Las tres leyes se combinan en una sola: <b>PV = nRT</b>, donde n es la cantidad de gas en moles y R = 0,082 atm·L/(mol·K).',
   'Un <b>gas ideal</b> supone que las partículas no ocupan volumen y no se atraen. Los gases reales se parecen al ideal a presiones bajas y temperaturas altas.'],
  key:'PV = nRT relaciona las cuatro variables de un gas.',
  co:'',
  act:{type:'calc',prompt:'¿Qué volumen ocupan 2 mol de gas a 27 °C y 0,74 atm (la presión atmosférica de Bogotá)?',steps:[{q:'Temperatura en Kelvin',help:'K = °C + 273',unit:'K',ans:300,how:'27 + 273 = 300 K'},{q:'Producto n × R × T',help:'2 × 0,082 × 300',unit:'atm·L',ans:49.2,how:'2 × 0,082 × 300 = 49,2'},{q:'Volumen V = nRT ÷ P',help:'Divide entre 0,74 atm',unit:'L',ans:66.5,tol:.5,how:'49,2 ÷ 0,74 ≈ 66,5 L'}]},
  quiz:[{q:'En PV = nRT, la letra n representa…',o:['El número de partículas','La cantidad de sustancia en moles','La densidad'],a:1,e:'n se mide en moles.'},
   {q:'Un gas real se comporta más como ideal cuando…',o:['La presión es alta y la temperatura baja','La presión es baja y la temperatura alta','Siempre'],a:1,e:'Las partículas están lejos y rápidas: casi no se atraen.'},
   {q:'Si n y T no cambian y P se triplica, V…',o:['Se triplica','Se reduce a la tercera parte','No cambia'],a:1,e:'PV = constante.'}]}
]},
{id:'g8u3',title:'Cantidad de sustancia',desc:'Masa, peso, mol y densidad.',lessons:[
 {id:'g8u3l1',title:'Masa, peso y el mol',time:55,std:'Comparo masa, peso, cantidad de sustancia y densidad de diferentes materiales.',dba:'',
  body:['La <b>masa</b> es la cantidad de materia (en kg). El <b>peso</b> es la fuerza con que la gravedad atrae esa masa (en newtons). En la Luna tu masa es la misma, pero pesas menos.',
   'Los átomos son tan pequeños que los químicos los cuentan por paquetes: un <b>mol</b> son 6,02 × 10²³ partículas (número de Avogadro).',
   'La <b>masa molar</b> es la masa de un mol, en g/mol. Se obtiene sumando las masas atómicas: H₂O = 2(1) + 16 = 18 g/mol.'],
  key:'Un mol es una “docena gigante”: 6,02 × 10²³ partículas.',
  co:'Una cucharada de agua (18 mL) contiene aproximadamente un mol de moléculas.',
  act:{type:'calc',prompt:'¿Cuántas moléculas hay en 36 g de agua?',data:'Masas atómicas: H = 1, O = 16. Avogadro = 6,02 × 10²³.',steps:[{q:'Masa molar del H₂O',help:'2 × 1 + 16',unit:'g/mol',ans:18,how:'18 g/mol'},{q:'Moles en 36 g',help:'moles = masa ÷ masa molar',unit:'mol',ans:2,how:'36 ÷ 18 = 2 mol'},{q:'Moléculas (escribe el número que multiplica a 10²³)',help:'2 × 6,02',unit:'× 10²³',ans:12.04,tol:.05,how:'2 × 6,02 × 10²³ = 12,04 × 10²³'}]},
  quiz:[{q:'Si viajas a la Luna, tu masa…',o:['Disminuye','Aumenta','Es la misma'],a:2,e:'Cambia el peso, no la masa.'},
   {q:'La masa molar del CO₂ (C = 12, O = 16) es…',o:['28 g/mol','44 g/mol','32 g/mol','12 g/mol'],a:1,e:'12 + 2 × 16 = 44.'},
   {q:'Un mol de cualquier sustancia tiene…',o:['1 g','6,02 × 10²³ partículas','22 L siempre'],a:1,e:'Es un número fijo de partículas.'}]},
 {id:'g8u3l2',title:'Densidad de materiales',time:45,std:'Comparo masa, peso, cantidad de sustancia y densidad de diferentes materiales.',dba:'',
  body:['La densidad permite identificar materiales y predecir si flotan. Se calcula con d = m ÷ V.',
   'Los metales suelen ser densos (hierro 7,87 g/cm³, oro 19,3 g/cm³). Los plásticos y maderas son menos densos.',
   'La densidad de un gas depende mucho de la presión y la temperatura: el aire caliente es menos denso y sube.'],
  key:'Densidad = masa ÷ volumen. Sirve como “huella” de un material.',
  co:'Los mineros artesanales del Chocó separan el oro con la batea porque es mucho más denso que la arena.',
  act:{type:'density',prompt:'Usa el simulador para responder.',ask:[{q:'¿Qué masa tiene un bloque de oro de 50 cm³?',a:965,tol:5,unit:'g'},{q:'¿Cuántos materiales de la lista flotan en agua?',a:3,tol:0,unit:'',h:'Prueba cada material.'}]},
  quiz:[{q:'¿Por qué el oro se queda en el fondo de la batea?',o:['Porque es brillante','Porque es mucho más denso que la arena','Porque es magnético'],a:1,e:'19,3 g/cm³ frente a unos 2,6 de la arena.'},
   {q:'Un material de 5 g/cm³ en agua…',o:['Flota','Se hunde'],a:1,e:'Es más denso que el agua.'},
   {q:'Un globo de aire caliente sube porque…',o:['El aire caliente es menos denso','Tiene helio','El fuego lo empuja'],a:0,e:'Al calentarse el aire se expande y su densidad baja.'}]}
]}
]};
export default grade;
