// Contenido del grado 9° (Estándares MEN 2004, DBA 2016)
import type { Grade } from './types';
const grade: Grade = 
{id:'g9',n:9,title:'Soluciones, ácidos y bases',desc:'Cómo se disuelven las sustancias, cómo se mide la concentración y qué es el pH.',units:[
{id:'g9u1',title:'Soluciones',desc:'Soluto, solvente, solubilidad y concentración.',lessons:[
 {id:'g9u1l1',title:'Soluto, solvente y solubilidad',time:50,std:'Establezco relaciones cuantitativas entre los componentes de una solución.',dba:'DBA 9°: analiza las relaciones cuantitativas entre solutos y solventes, así como los factores que afectan la formación de soluciones.',
  body:['Una <b>solución</b> es una mezcla homogénea. El <b>solvente</b> es el componente en mayor cantidad (casi siempre agua) y el <b>soluto</b> el que se disuelve.',
   'La <b>solubilidad</b> es la máxima cantidad de soluto que se disuelve en una cantidad de solvente a cierta temperatura. Para la sal de cocina es unos 36 g por cada 100 mL de agua.',
   'Una solución <b>saturada</b> ya no disuelve más soluto; lo que sobra se queda en el fondo. La temperatura suele aumentar la solubilidad de los sólidos y disminuir la de los gases.'],
  key:'Solvente disuelve, soluto se disuelve. La solubilidad tiene un límite.',
  co:'La gaseosa pierde gas más rápido caliente: el CO₂ es menos soluble a mayor temperatura.',
  act:{type:'conc',prompt:'Agrega sal y cambia el volumen. Encuentra el punto de saturación.',ask:[{q:'Con 250 mL de solución, ¿cuántos gramos de sal se pueden disolver como máximo?',a:90,tol:1,unit:'g',h:'Busca el valor donde empiezan a aparecer cristales sin disolver.'},{q:'Si agregas 50 g de sal a 100 mL, la solución está…',o:['Diluida','Saturada con exceso de sal','Sin soluto'],a:1}]},
  quiz:[{q:'En el agua de panela, el solvente es…',o:['La panela','El agua','El vaso'],a:1,e:'El agua está en mayor cantidad.'},
   {q:'Una solución saturada…',o:['No puede disolver más soluto a esa temperatura','No tiene soluto','Es heterogénea siempre'],a:0,e:'Llegó al límite de solubilidad.'},
   {q:'¿Por qué la gaseosa caliente pierde gas más rápido?',o:['El gas es más soluble en caliente','El gas es menos soluble en caliente','El azúcar lo expulsa'],a:1,e:'La solubilidad de los gases baja con la temperatura.'}]},
 {id:'g9u1l2',title:'Concentración en porcentaje y ppm',time:55,std:'Establezco relaciones cuantitativas entre los componentes de una solución.',dba:'DBA 9°: analiza las relaciones cuantitativas entre solutos y solventes.',
  body:['La <b>concentración</b> dice cuánto soluto hay en cierta cantidad de solución.',
   '<b>% m/m</b> = (masa de soluto ÷ masa de solución) × 100. <b>% m/v</b> = (gramos de soluto ÷ mL de solución) × 100. <b>% v/v</b> se usa en líquidos, como el alcohol de las bebidas.',
   'Para cantidades muy pequeñas se usan <b>partes por millón (ppm)</b>: mg de soluto por litro de agua. Así se mide el cloro del agua potable.'],
  key:'Concentración = soluto ÷ solución. Cambia la unidad según el uso.',
  co:'En Colombia la norma de agua potable permite entre 0,3 y 2 mg/L (ppm) de cloro residual libre.',
  act:{type:'calc',prompt:'Preparas un suero casero con 9 g de sal en 1.000 mL de solución. ¿Cuál es su concentración?',steps:[{q:'% m/v',help:'(9 ÷ 1.000) × 100',unit:'%',ans:.9,how:'0,9 % m/v, igual que el suero fisiológico'},{q:'Si solo tienes 250 mL, ¿cuánta sal usas para la misma concentración?',help:'0,9 g por cada 100 mL',unit:'g',ans:2.25,how:'250 × 0,9 ÷ 100 = 2,25 g'}]},
  quiz:[{q:'Una cerveza de 4 % v/v tiene en 100 mL…',o:['4 g de alcohol','4 mL de alcohol','96 mL de alcohol'],a:1,e:'v/v: volumen de soluto por 100 de solución.'},
   {q:'20 g de azúcar en 200 mL de solución: % m/v =',o:['10 %','20 %','4 %','0,1 %'],a:0,e:'(20 ÷ 200) × 100 = 10 %.'},
   {q:'1 ppm en agua equivale a…',o:['1 g/L','1 mg/L','1 kg/L'],a:1,e:'Un miligramo por litro.'}]},
 {id:'g9u1l3',title:'Molaridad',time:55,std:'Establezco relaciones cuantitativas entre los componentes de una solución.',dba:'DBA 9°: analiza las relaciones cuantitativas entre solutos y solventes.',
  body:['La <b>molaridad (M)</b> es la cantidad de moles de soluto por litro de solución: M = moles ÷ litros.',
   'Para NaCl (masa molar 58,5 g/mol), 58,5 g en 1 L forman una solución 1 M.',
   'Al <b>diluir</b> se agrega solvente: los moles de soluto no cambian, pero la concentración baja. M₁ × V₁ = M₂ × V₂.'],
  key:'Molaridad = moles de soluto por litro de solución.',
  co:'',
  act:{type:'conc',prompt:'Usa el simulador para encontrar soluciones con la molaridad pedida.',ask:[{q:'¿Cuántos gramos de sal necesitas en 500 mL para una solución 1 M? (redondea)',a:29,tol:1,unit:'g',h:'Mira la lectura de molaridad mientras mueves la sal.'},{q:'Con 20 g de sal, ¿qué pasa con la molaridad si pasas de 250 mL a 500 mL?',o:['Se duplica','Se reduce a la mitad','No cambia'],a:1,e:'Mismos moles en el doble de volumen.'}]},
  quiz:[{q:'2 mol de soluto en 4 L de solución dan…',o:['8 M','0,5 M','2 M'],a:1,e:'2 ÷ 4 = 0,5 M.'},
   {q:'Al diluir una solución, los moles de soluto…',o:['Aumentan','Disminuyen','No cambian'],a:2,e:'Solo se agrega solvente.'},
   {q:'100 mL de HCl 2 M se diluyen hasta 400 mL. Nueva concentración:',o:['0,5 M','8 M','1 M'],a:0,e:'2 × 100 = M₂ × 400 → M₂ = 0,5 M.'}]}
]},
{id:'g9u2',title:'Ácidos y bases',desc:'Definiciones, pH y neutralización.',lessons:[
 {id:'g9u2l1',title:'Modelos de ácidos y bases',time:50,std:'Comparo los modelos que sustentan la definición ácido-base.',dba:'DBA 9°: comprende que la acidez y la basicidad son propiedades químicas de algunas sustancias.',
  body:['Según <b>Arrhenius</b>, un ácido libera iones H⁺ en agua (HCl → H⁺ + Cl⁻) y una base libera OH⁻ (NaOH → Na⁺ + OH⁻).',
   'Según <b>Brønsted-Lowry</b>, un ácido <b>dona</b> un protón (H⁺) y una base lo <b>acepta</b>. Este modelo explica bases sin OH⁻, como el amoníaco (NH₃).',
   'Los ácidos tienen sabor agrio y reaccionan con metales; las bases tienen sabor amargo y son jabonosas. Nunca se prueban en el laboratorio.'],
  key:'Ácido: dona H⁺. Base: acepta H⁺ (o libera OH⁻).',
  co:'El ácido del limón y la naranja es el ácido cítrico; el de la leche agria, el ácido láctico.',
  act:{type:'classify',prompt:'¿Ácido o base?',bins:['Ácido','Base'],items:[['HCl (en el estómago)',0],['NaOH (soda cáustica)',1],['Vinagre (ácido acético)',0],['NH₃ (amoníaco)',1],['Jugo de limón',0],['Leche de magnesia',1],['H₂SO₄ (batería de carro)',0]]},
  quiz:[{q:'Según Brønsted-Lowry, una base…',o:['Dona protones','Acepta protones','Libera electrones'],a:1,e:'Acepta H⁺.'},
   {q:'¿Qué ion libera un ácido de Arrhenius en agua?',o:['OH⁻','H⁺','Na⁺','Cl⁻'],a:1,e:'Ese H⁺ es responsable de la acidez.'},
   {q:'El NH₃ es base de Brønsted porque…',o:['Tiene OH','Acepta un H⁺ y forma NH₄⁺','Es un gas'],a:1,e:'Su par libre de electrones captura el protón.'}]},
 {id:'g9u2l2',title:'La escala de pH',time:55,std:'Identifico productos que pueden tener diferentes niveles de pH y explico algunos de sus usos en actividades cotidianas.',dba:'DBA 9°: comprende que la acidez y la basicidad son propiedades químicas de algunas sustancias.',
  body:['El <b>pH</b> mide la acidez: pH = −log[H⁺]. Va de 0 a 14. Menor que 7 es ácido, 7 es neutro y mayor que 7 es básico.',
   'Cada unidad de pH es un factor de 10: pH 3 es diez veces más ácido que pH 4 y cien veces más que pH 5.',
   'Los <b>indicadores</b> cambian de color según el pH. El repollo morado es un indicador casero: rojo en ácidos, morado en neutros y verde o amarillo en bases fuertes.'],
  key:'pH bajo = mucho H⁺ = ácido. Cada punto es ×10.',
  co:'Muchos suelos cafeteros colombianos son ácidos (pH 4,5 a 5,5) y se les aplica cal para subir el pH.',
  act:{type:'ph',prompt:'Toca cada sustancia y mira el pH y el color del indicador de repollo.',ask:[{q:'¿Cuál es el pH del vinagre según el simulador?',a:2.9,tol:.05},{q:'¿Cuántas sustancias de la lista son básicas?',a:7,tol:0,h:'Cuenta todas las que tienen pH mayor que 7.'},{q:'El limón (pH 2,2) comparado con el café (pH 5)…',o:['Es menos ácido','Es más ácido, cerca de 1.000 veces','Tiene la misma acidez'],a:1,e:'Casi 3 unidades de diferencia: 10 × 10 × 10.'}]},
  quiz:[{q:'Una solución de pH 9 es…',o:['Ácida','Neutra','Básica'],a:2,e:'Mayor que 7.'},
   {q:'¿Cuántas veces más ácido es pH 2 que pH 4?',o:['2','20','100'],a:2,e:'Dos unidades: 10 × 10.'},
   {q:'El agua pura a 25 °C tiene pH…',o:['0','7','14'],a:1,e:'Neutra.'}],
  tip:'Prepare extracto de repollo morado (hervir hojas en agua) y pruébelo con productos de la cocina.'},
 {id:'g9u2l3',title:'Neutralización',time:50,std:'Comparo los modelos que sustentan la definición ácido-base.',dba:'DBA 9°: comprende que la acidez y la basicidad son propiedades químicas de algunas sustancias.',
  body:['Cuando un ácido reacciona con una base se forman <b>sal y agua</b>. Esta reacción se llama <b>neutralización</b>: HCl + NaOH → NaCl + H₂O.',
   'El H⁺ del ácido y el OH⁻ de la base se unen para formar agua. Lo que queda forma la sal.',
   'Los antiácidos neutralizan el exceso de ácido del estómago. La cal neutraliza suelos ácidos.'],
  key:'Ácido + base → sal + agua.',
  co:'',
  act:{type:'balance',prompt:'Balancea las neutralizaciones.',rx:[{name:'Ácido clorhídrico + soda',r:['HCl','NaOH'],p:['NaCl','H2O'],c:[1,1,1,1]},{name:'Antiácido',r:['HCl','Mg(OH)2'],p:['MgCl2','H2O'],c:[2,1,1,2]},{name:'Batería de carro',r:['H2SO4','NaOH'],p:['Na2SO4','H2O'],c:[1,2,1,2]}]},
  quiz:[{q:'Los productos de una neutralización son…',o:['Ácido y base','Sal y agua','Óxido y agua'],a:1,e:'Es la regla general.'},
   {q:'La leche de magnesia, Mg(OH)₂, alivia la acidez porque…',o:['Es un ácido','Es una base que neutraliza el HCl del estómago','Es azúcar'],a:1,e:'Reacción ácido-base.'},
   {q:'En HCl + NaOH → NaCl + H₂O, la sal es…',o:['HCl','NaOH','NaCl','H₂O'],a:2,e:'Cloruro de sodio.'}]}
]},
{id:'g9u3',title:'Química y ambiente',desc:'Contaminación del aire y química de productos cotidianos.',lessons:[
 {id:'g9u3l1',title:'Contaminación atmosférica',time:50,std:'Describo procesos físicos y químicos de la contaminación atmosférica.',dba:'',
  body:['Los combustibles fósiles liberan <b>CO₂</b>, que atrapa calor en la atmósfera (efecto invernadero). También liberan <b>óxidos de azufre y nitrógeno</b>, que con el agua forman ácidos y producen <b>lluvia ácida</b>.',
   'El <b>material particulado</b> (PM2,5) son partículas tan pequeñas que entran a los pulmones. Viene del diésel, las quemas y la industria.',
   'El <b>ozono troposférico</b> se forma cuando la luz del sol actúa sobre los gases de los carros.'],
  key:'Quemar combustibles fósiles libera gases que calientan el planeta y acidifican la lluvia.',
  co:'Bogotá y Medellín declaran alertas ambientales por PM2,5, sobre todo entre febrero y marzo, cuando el aire circula menos.',
  act:{type:'classify',prompt:'¿Qué problema causa cada contaminante principalmente?',bins:['Efecto invernadero','Lluvia ácida','Daño respiratorio'],items:[['CO₂ del exosto',0],['SO₂ de carbón con azufre',1],['PM2,5 del diésel',2],['Metano de la ganadería',0],['NO₂ de los motores',1],['Humo de quemas agrícolas',2]]},
  quiz:[{q:'La lluvia ácida se forma por…',o:['CO₂ y oxígeno','Óxidos de azufre y nitrógeno con agua','Ozono y nitrógeno'],a:1,e:'Forman H₂SO₄ y HNO₃.'},
   {q:'El PM2,5 es peligroso porque…',o:['Huele mal','Entra profundo en los pulmones','Es radiactivo'],a:1,e:'Su tamaño (menos de 2,5 micras) le permite llegar a los alvéolos.'},
   {q:'El principal gas de efecto invernadero de origen humano es…',o:['O₂','N₂','CO₂'],a:2,e:'Proviene de la quema de combustibles.'}]},
 {id:'g9u3l2',title:'La química de las etiquetas',time:45,std:'Comparo información química de las etiquetas de productos manufacturados por diferentes casas comerciales.',dba:'',
  body:['Las etiquetas indican ingredientes, concentraciones y advertencias. Aprender a leerlas es una competencia científica ciudadana.',
   'Los pictogramas del <b>Sistema Globalmente Armonizado</b> indican peligros: corrosivo, inflamable, tóxico, irritante.',
   'Nunca se deben mezclar blanqueador (hipoclorito) y amoníaco o ácidos: se liberan gases tóxicos como cloraminas o cloro.'],
  key:'Leer la etiqueta es la primera medida de seguridad química.',
  co:'El INVIMA exige registro sanitario y etiquetado en español para los productos de aseo que se venden en Colombia.',
  act:{type:'ph',prompt:'Explora los productos de aseo y cocina.',ask:[{q:'¿Cuál de estos es más corrosivo por su pH?',o:['Leche','Soda cáustica','Agua pura'],a:1},{q:'¿Qué pH tiene el blanqueador según el simulador?',a:12.5,tol:.05}]},
  quiz:[{q:'¿Qué NO se debe mezclar nunca?',o:['Agua y jabón','Blanqueador y amoníaco','Sal y agua'],a:1,e:'Forman gases tóxicos.'},
   {q:'El pictograma de una mano corroída indica…',o:['Inflamable','Corrosivo','Explosivo'],a:1,e:'Daña piel y metales.'},
   {q:'Un limpiador con pH 13 es…',o:['Muy ácido','Neutro','Muy básico'],a:2,e:'Cercano a 14.'}]}
]}
]};
export default grade;
