// Juegos de la sección "Juega" de cada lección (grados 9° a 11°). Dos por lección.
export const LESSON_GAMES_B = {
  /* ===================== GRADO 9° ===================== */
  g9u1l1: [
    { game: 'sorter', title: '¿Soluto o solvente?', time: 60, bins: ['Soluto', 'Solvente'], items: [
      ['Panela en aguapanela', 0], ['Agua en aguapanela', 1], ['Sal en el suero', 0], ['Agua en el suero', 1],
      ['CO₂ en la gaseosa', 0], ['Agua en la gaseosa', 1], ['Azúcar en el tinto', 0], ['Oxígeno en el aire', 0],
      ['Nitrógeno en el aire', 1], ['Zinc en el latón', 0], ['Cobre en el latón', 1], ['Yodo en la tintura de yodo', 0],
      ['Alcohol en la tintura de yodo', 1], ['Café soluble en el tinto', 0] ] },
    { game: 'truefalse', title: 'Mitos de las soluciones', time: 60, lives: 3, items: [
      { s: 'El solvente siempre es agua.', a: false, e: 'Es el componente en mayor cantidad: en el aire, el solvente es el nitrógeno.' },
      { s: 'Una solución es una mezcla homogénea.', a: true, e: 'Se ve igual en todas sus partes.' },
      { s: 'Si revuelves suficiente, puedes disolver sal sin límite.', a: false, e: 'Revolver acelera, pero la solubilidad tiene un límite (unos 36 g por 100 mL).' },
      { s: 'En una solución saturada, la sal que sobra se queda en el fondo.', a: true, e: 'Ya no se puede disolver más a esa temperatura.' },
      { s: 'Los gases se disuelven mejor en agua caliente.', a: false, e: 'Es al revés: la solubilidad de los gases baja al subir la temperatura.' },
      { s: 'Calentar el agua suele permitir disolver más azúcar.', a: true, e: 'La solubilidad de la mayoría de los sólidos aumenta con la temperatura.' },
      { s: 'Cuando el azúcar se disuelve en el tinto, desaparece.', a: false, e: 'Sus moléculas se dispersan entre las del agua: por eso el tinto queda dulce.' },
      { s: 'El soluto es el componente que está en mayor cantidad.', a: false, e: 'Ese es el solvente; el soluto es el que se disuelve.' },
      { s: 'En días muy calurosos, el agua de un estanque tiene menos oxígeno disuelto.', a: true, e: 'El O₂ es un gas: se disuelve menos en agua caliente.' },
      { s: 'Una aguapanela bien mezclada es igual de dulce arriba y abajo.', a: true, e: 'Es homogénea: la concentración es la misma en todo el vaso.' },
      { s: 'El aire es una solución de gases.', a: true, e: 'Es una mezcla homogénea con nitrógeno como solvente.' } ] },
  ],
  g9u1l2: [
    { game: 'blitz', title: 'Contrarreloj de concentraciones', time: 60, lives: 3, items: [
      { q: '15 g de sal en 300 mL de solución. ¿% m/v?', o: ['5 %', '20 %', '0,05 %', '45 %'], a: 0, e: '(15 ÷ 300) × 100 = 5 %.' },
      { q: '25 g de azúcar + 75 g de agua. ¿% m/m?', o: ['33 %', '25 %', '75 %', '2,5 %'], a: 1, e: 'La solución pesa 100 g: (25 ÷ 100) × 100 = 25 %.' },
      { q: 'Un vino de 12 % v/v. ¿Cuánto alcohol hay en 750 mL?', o: ['12 mL', '90 mL', '75 mL', '62,5 mL'], a: 1, e: '750 × 12 ÷ 100 = 90 mL.' },
      { q: 'Un agua con 0,8 mg de cloro en 2 L tiene…', o: ['0,4 ppm', '1,6 ppm', '0,8 ppm', '4 ppm'], a: 0, e: 'ppm = mg ÷ L = 0,8 ÷ 2 = 0,4.' },
      { q: '¿Cuántos gramos de soluto hay en 200 g de solución al 5 % m/m?', o: ['5 g', '10 g', '40 g', '20 g'], a: 1, e: '200 × 5 ÷ 100 = 10 g.' },
      { q: 'La norma pide 0,3 a 2 ppm de cloro. Una muestra con 3 mg/L…', o: ['Cumple la norma', 'Tiene exceso de cloro', 'Tiene muy poco cloro', 'No tiene cloro'], a: 1, e: '3 mg/L = 3 ppm, por encima de 2 ppm.' },
      { q: '¿Qué unidad usarías para el plomo disuelto en un río?', o: ['% v/v', 'ppm', '% m/m', 'Litros'], a: 1, e: 'Para cantidades muy pequeñas se usan partes por millón.' },
      { q: 'Para 500 mL de suero al 0,9 % m/v necesitas…', o: ['0,9 g de sal', '4,5 g de sal', '9 g de sal', '45 g de sal'], a: 1, e: '500 × 0,9 ÷ 100 = 4,5 g.' },
      { q: 'Alcohol antiséptico al 70 % v/v: en 100 mL hay…', o: ['70 g de alcohol', '70 mL de alcohol', '30 mL de alcohol', '7 mL de alcohol'], a: 1, e: 'v/v: mililitros de soluto por cada 100 mL de solución.' },
      { q: 'Con el mismo soluto, si el volumen de solución se duplica, el % m/v…', o: ['Se duplica', 'Se reduce a la mitad', 'No cambia', 'Se vuelve cero'], a: 1, e: 'Misma masa de soluto en el doble de volumen.' } ] },
    { game: 'catcher', title: 'Inspector del agua potable', time: 45, lives: 3,
      rule: 'Atrapa solo el agua con cloro dentro de la norma (0,3 a 2 ppm)',
      good: ['0,5 ppm', '1 ppm', '1,5 mg/L', '1,8 ppm', '0,4 mg/L', '1,2 ppm', '0,8 mg/L', '3 mg en 2 L', '1 mg en 1 L'],
      bad: ['0,1 ppm', '3 ppm', '5 mg/L', '0 mg/L', '2,5 ppm', '10 ppm', '0,2 mg/L', '6 mg en 2 L', '1 mg en 10 L'] },
  ],
  g9u1l3: [
    { game: 'memory', title: 'Parejas molares', pairs: [
      ['2 mol en 4 L', '0,5 M'], ['3 mol en 1 L', '3 M'], ['0,1 mol en 100 mL', '1 M'], ['1 mol en 5 L', '0,2 M'],
      ['117 g de NaCl en 1 L', '2 M'], ['0,5 mol en 2 L', '0,25 M'], ['4 g de NaOH en 1 L', '0,1 M'], ['M₁ × V₁ = M₂ × V₂', 'Ecuación de dilución'] ] },
    { game: 'order', title: 'Ordena por molaridad', time: 90, rounds: [
      { prompt: 'Ordena de menor a mayor molaridad', items: ['1 mol en 4 L', '0,5 mol en 1 L', '2 mol en 2 L', '3 mol en 2 L', '1 mol en 250 mL'], labels: ['0,25 M', '0,5 M', '1 M', '1,5 M', '4 M'] },
      { prompt: 'NaCl (58,5 g/mol): ordena de menor a mayor molaridad', items: ['11,7 g en 1 L', '29,25 g en 1 L', '58,5 g en 1 L', '58,5 g en 500 mL', '175,5 g en 1 L'], labels: ['0,2 M', '0,5 M', '1 M', '2 M', '3 M'] },
      { prompt: 'Ordena los pasos para preparar 250 mL de NaCl 1 M', items: ['Calcular los moles: 0,25 mol', 'Pasar a gramos: 14,6 g', 'Pesar la sal', 'Disolver en poca agua', 'Completar hasta 250 mL'] },
      { prompt: 'Tienes 100 mL de HCl 2 M. Ordena de mayor a menor concentración al diluir hasta…', items: ['100 mL', '200 mL', '400 mL', '1 L'], labels: ['2 M', '1 M', '0,5 M', '0,2 M'] } ] },
  ],
  g9u2l1: [
    { game: 'word', title: 'Palabra ácida', lives: 6, words: [
      { w: 'PROTÓN', h: 'El ion H⁺ es, en realidad, esta partícula que un ácido dona' },
      { w: 'ARRHENIUS', h: 'Su modelo: el ácido libera H⁺ y la base libera OH⁻ en agua' },
      { w: 'AMONÍACO', h: 'Base sin OH⁻ que acepta un H⁺ y forma NH₄⁺' },
      { w: 'HIDRÓXIDO', h: 'Nombre del ion OH⁻ que liberan las bases de Arrhenius' },
      { w: 'AGRIO', h: 'Sabor típico de los ácidos (¡nunca se prueba en el laboratorio!)' },
      { w: 'AMARGO', h: 'Sabor típico de las bases, que además se sienten jabonosas' },
      { w: 'CÍTRICO', h: 'Ácido del limón y la naranja' },
      { w: 'LÁCTICO', h: 'Ácido de la leche agria' } ] },
    { game: 'memory', title: 'Parejas de Arrhenius y Brønsted', pairs: [
      ['Ácido de Arrhenius', 'Libera H⁺ en agua'], ['Base de Arrhenius', 'Libera OH⁻ en agua'], ['Ácido de Brønsted', 'Dona un protón'],
      ['Base de Brønsted', 'Acepta un protón'], ['NH₃ + H⁺', 'NH₄⁺ (amonio)'], ['Ácido cítrico', 'Limón y naranja'],
      ['Ácido láctico', 'Leche agria'], ['Sabor amargo, jabonoso', 'Base'] ] },
  ],
  g9u2l2: [
    { game: 'order', title: 'La escalera del pH', time: 90, rounds: [
      { prompt: 'Ordena del más ácido al más básico', items: ['Jugo gástrico', 'Vinagre', 'Café', 'Agua pura', 'Bicarbonato en agua', 'Leche de magnesia'], labels: ['pH 1,5', 'pH 2,9', 'pH 5', 'pH 7', 'pH 8,3', 'pH 10,5'] },
      { prompt: 'Ordena de menor a mayor concentración de H⁺', items: ['pH 13', 'pH 10', 'pH 7', 'pH 4', 'pH 1'] },
      { prompt: 'Ordena los colores del repollo morado de pH bajo a pH alto', items: ['Rojo', 'Morado', 'Verde', 'Amarillo'], labels: ['Ácido', 'Neutro', 'Básico', 'Muy básico'] } ] },
    { game: 'truefalse', title: '¿Verdad o mito del pH?', time: 60, lives: 3, items: [
      { s: 'Una solución de pH 3 es el doble de ácida que una de pH 6.', a: false, e: 'Son 3 unidades: 10 × 10 × 10 = 1.000 veces más ácida.' },
      { s: 'Un pH menor que 7 indica una solución ácida.', a: true, e: 'Por debajo de 7 hay más H⁺ que OH⁻.' },
      { s: 'El agua pura (pH 7) no tiene iones H⁺.', a: false, e: 'Tiene H⁺ y OH⁻ en igual cantidad; por eso es neutra.' },
      { s: 'Pasar de pH 5 a pH 4 multiplica por 10 la concentración de H⁺.', a: true, e: 'Cada unidad de pH es un factor de 10.' },
      { s: 'El extracto de repollo morado se pone verde o amarillo en bases fuertes.', a: true, e: 'Es rojo en ácidos, morado en neutros y verde o amarillo en bases.' },
      { s: 'A mayor pH, mayor concentración de H⁺.', a: false, e: 'Es al revés: pH alto significa poco H⁺.' },
      { s: 'Echar cal a un suelo cafetero ácido sube su pH.', a: true, e: 'La cal es básica y neutraliza la acidez del suelo.' },
      { s: 'Todo lo que tiene pH bajo es peligroso para comer.', a: false, e: 'El limón (pH 2,2) y el vinagre son ácidos y los consumimos a diario.' },
      { s: 'La leche de magnesia es básica.', a: true, e: 'Su pH es cerca de 10,5.' },
      { s: 'La escala de pH va solo de 1 a 10.', a: false, e: 'En soluciones acuosas comunes va de 0 a 14.' },
      { s: 'La sangre humana es ligeramente básica.', a: true, e: 'Su pH es cerca de 7,4.' } ] },
  ],
  g9u2l3: [
    { game: 'balancer', title: 'Balanceo de neutralizaciones', rx: [
      { r: ['HNO3', 'KOH'], p: ['KNO3', 'H2O'], c: [1, 1, 1, 1] },
      { r: ['HCl', 'Ca(OH)2'], p: ['CaCl2', 'H2O'], c: [2, 1, 1, 2] },
      { r: ['H2SO4', 'Ca(OH)2'], p: ['CaSO4', 'H2O'], c: [1, 1, 1, 2] },
      { r: ['HCl', 'Al(OH)3'], p: ['AlCl3', 'H2O'], c: [3, 1, 1, 3] },
      { r: ['H2SO4', 'KOH'], p: ['K2SO4', 'H2O'], c: [1, 2, 1, 2] },
      { r: ['HNO3', 'Mg(OH)2'], p: ['Mg(NO3)2', 'H2O'], c: [2, 1, 1, 2] },
      { r: ['H3PO4', 'NaOH'], p: ['Na3PO4', 'H2O'], c: [1, 3, 1, 3] } ] },
    { game: 'blitz', title: 'Contrarreloj de neutralización', time: 60, lives: 3, items: [
      { q: 'HNO₃ + KOH → ? + H₂O. La sal es…', o: ['KNO₃', 'KOH', 'HNO₃', 'K₂O'], a: 0, e: 'Nitrato de potasio: el K de la base reemplaza al H del ácido.' },
      { q: 'En toda neutralización, el H⁺ y el OH⁻ forman…', o: ['Sal', 'Agua', 'Oxígeno', 'Hidrógeno gaseoso'], a: 1, e: 'H⁺ + OH⁻ → H₂O.' },
      { q: '¿Qué se usa en el campo para neutralizar suelos ácidos?', o: ['Vinagre', 'Cal', 'Ácido sulfúrico', 'Azúcar'], a: 1, e: 'La cal es básica.' },
      { q: 'Si mezclas cantidades equivalentes de HCl y NaOH, el pH final queda cerca de…', o: ['1', '7', '14', '3'], a: 1, e: 'Solo quedan NaCl y agua: solución neutra.' },
      { q: 'Un buen antiácido es…', o: ['Un ácido fuerte', 'Una base suave', 'Agua con sal', 'Jugo de limón'], a: 1, e: 'Neutraliza el exceso de HCl sin dañar el estómago.' },
      { q: 'HCl + KOH produce…', o: ['KCl + H₂O', 'KH + HClO', 'K + HCl', 'KClO + H₂'], a: 0, e: 'Ácido + base → sal + agua.' },
      { q: 'H₂SO₄ + Ca(OH)₂ → CaSO₄ + 2 H₂O. ¿Qué sal se forma?', o: ['CaSO₄', 'H₂O', 'Ca(OH)₂', 'H₂SO₄'], a: 0, e: 'Sulfato de calcio, el mismo del yeso.' },
      { q: 'Al agregar poco a poco una base a un ácido, el pH…', o: ['Baja', 'Sube', 'No cambia', 'Llega a 0'], a: 1, e: 'Cada vez hay menos H⁺ libre.' },
      { q: '¿Cuántos OH⁻ aporta cada unidad de Mg(OH)₂?', o: ['1', '2', '3', '4'], a: 1, e: 'El subíndice 2 afecta a todo el grupo OH.' },
      { q: 'Para neutralizar 1 H₂SO₄ se necesitan … NaOH', o: ['1', '2', '3', '4'], a: 1, e: 'El H₂SO₄ tiene 2 H⁺ que neutralizar.' } ] },
  ],
  g9u3l1: [
    { game: 'builder', title: 'Arma los contaminantes del aire', targets: ['CO2', 'CH4', 'SO2', 'NO2', 'O3', 'CO', 'SO3'], palette: ['C', 'H', 'N', 'O', 'S'] },
    { game: 'truefalse', title: 'Aire limpio: ¿verdad o mito?', time: 60, lives: 3, items: [
      { s: 'El CO₂ atrapa calor en la atmósfera.', a: true, e: 'Es el principal gas de efecto invernadero de origen humano.' },
      { s: 'La lluvia ácida se debe principalmente al CO₂.', a: false, e: 'Se debe sobre todo a óxidos de azufre y nitrógeno, que forman H₂SO₄ y HNO₃.' },
      { s: 'El PM2,5 son partículas de menos de 2,5 micras.', a: true, e: 'Por su tamaño llegan hasta los alvéolos.' },
      { s: 'El ozono cerca del suelo es beneficioso porque nos protege de los rayos UV.', a: false, e: 'Cerca del suelo es un contaminante; el ozono que protege está en la estratosfera.' },
      { s: 'El ozono troposférico se forma por la luz solar sobre los gases de los carros.', a: true, e: 'Es un contaminante secundario, típico de días soleados con tráfico.' },
      { s: 'El metano de la ganadería es un gas de efecto invernadero.', a: true, e: 'El CH₄ atrapa calor con mucha eficacia.' },
      { s: 'Los motores diésel son una fuente de material particulado.', a: true, e: 'El hollín del diésel es PM2,5.' },
      { s: 'Quemar carbón que contiene azufre libera SO₂.', a: true, e: 'S + O₂ → SO₂, que luego forma lluvia ácida.' },
      { s: 'El efecto invernadero y la lluvia ácida son el mismo fenómeno.', a: false, e: 'Uno calienta el planeta (CO₂, CH₄); la otra acidifica el agua (SO₂, NO₂).' },
      { s: 'El O₂ es el principal gas de efecto invernadero.', a: false, e: 'El O₂ no atrapa calor; el principal de origen humano es el CO₂.' },
      { s: 'El material particulado solo viene de las fábricas.', a: false, e: 'También viene del diésel, las quemas agrícolas y los incendios.' } ] },
  ],
  g9u3l2: [
    { game: 'word', title: 'Palabras de la etiqueta', lives: 6, words: [
      { w: 'PICTOGRAMA', h: 'Dibujo dentro de un rombo rojo que advierte un peligro' },
      { w: 'CORROSIVO', h: 'Peligro que daña la piel y los metales; se dibuja con una mano afectada' },
      { w: 'INFLAMABLE', h: 'Peligro de los productos que arden con facilidad, como la gasolina' },
      { w: 'TÓXICO', h: 'Peligro que se representa con una calavera' },
      { w: 'HIPOCLORITO', h: 'Sustancia activa del blanqueador' },
      { w: 'CLORAMINAS', h: 'Gases dañinos que salen al mezclar blanqueador y amoníaco' },
      { w: 'INVIMA', h: 'Entidad que exige registro sanitario a los productos en Colombia' },
      { w: 'ETIQUETA', h: 'Lo primero que se lee antes de usar un producto químico' } ] },
    { game: 'blitz', title: 'Lee la etiqueta a tiempo', time: 60, lives: 3, items: [
      { q: 'Un producto con el pictograma de una llama es…', o: ['Corrosivo', 'Inflamable', 'Tóxico', 'Radiactivo'], a: 1, e: 'Arde con facilidad: lejos del fuego.' },
      { q: '¿Qué pasa si mezclas blanqueador con un limpiador ácido?', o: ['Limpia mejor', 'Libera cloro, un gas tóxico', 'Se neutraliza sin peligro', 'Forma solo agua'], a: 1, e: 'El hipoclorito con ácidos libera Cl₂.' },
      { q: 'La etiqueta dice "hipoclorito de sodio 5 %". Es…', o: ['Blanqueador', 'Vinagre', 'Jabón de manos', 'Alcohol'], a: 0, e: 'El hipoclorito es el activo de los blanqueadores.' },
      { q: 'Blanqueador A: 5,25 % de hipoclorito. B: 3 %. ¿Cuál está más concentrado?', o: ['A', 'B', 'Iguales', 'No se puede saber'], a: 0, e: 'Más gramos de soluto por cada 100 de producto.' },
      { q: '¿Qué entidad exige registro sanitario a productos de aseo en Colombia?', o: ['INVIMA', 'DIAN', 'ICFES', 'IDEAM'], a: 0, e: 'El INVIMA también exige etiquetado en español.' },
      { q: 'Un destapador de cañerías de pH 14 es…', o: ['Neutro', 'Muy ácido', 'Muy básico y corrosivo', 'Inofensivo'], a: 2, e: 'Un pH tan alto destruye tejidos.' },
      { q: 'Si un producto te salpica en los ojos, lo primero es…', o: ['Frotarlos', 'Lavar con abundante agua', 'Echar vinagre', 'Esperar a ver'], a: 1, e: 'Agua abundante y luego ayuda médica con la etiqueta en mano.' },
      { q: 'El pictograma de la calavera indica…', o: ['Toxicidad aguda', 'Inflamable', 'Corrosivo', 'Gas a presión'], a: 0, e: 'Pequeñas cantidades pueden causar daño grave.' },
      { q: '¿Por qué guardar los productos en su envase original?', o: ['Por estética', 'Para conservar la etiqueta y sus advertencias', 'Porque así no se evaporan', 'No importa'], a: 1, e: 'Evita confusiones e intoxicaciones.' },
      { q: 'Un jabón dice "pH 5,5". Es un producto…', o: ['Ligeramente ácido', 'Muy básico', 'Neutro', 'Corrosivo'], a: 0, e: 'Un poco menor que 7.' } ] },
  ],

  /* ===================== GRADO 10° ===================== */
  g10u1l1: [
    { game: 'hunter', title: 'Cazador de electrones de valencia', time: 90, clues: [
      { c: 'Mi configuración termina en 3p⁴', a: 'S' }, { c: 'Termino en 4s¹', a: 'K' }, { c: 'Termino en 2p¹', a: 'B' },
      { c: 'Termino en 3p¹', a: 'Al' }, { c: 'Termino en 2s² (y no tengo 2p)', a: 'Be' }, { c: 'Termino en 4p⁵', a: 'Br' },
      { c: 'Termino en 4s² 3d¹⁰', a: 'Zn' }, { c: 'Termino en 4p⁶: soy gas noble', a: 'Kr' }, { c: 'Termino en 4p¹', a: 'Ga' },
      { c: 'Termino en 4s² 3d¹', a: 'Sc' }, { c: 'Termino en 4p³', a: 'As' }, { c: 'Tengo 6 electrones de valencia en el nivel 2', a: 'O' },
      { c: 'Termino en 4s² y no tengo electrones d', a: 'Ca' }, { c: 'Tengo 5 electrones de valencia en el nivel 3', a: 'P' },
      { c: 'Soy 1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁵', a: 'Mn' } ] },
    { game: 'order', title: 'Diagonales en orden', time: 90, rounds: [
      { prompt: 'Ordena los subniveles según el orden de llenado (Aufbau)', items: ['2p', '3s', '3p', '4s', '3d', '4p'] },
      { prompt: 'Ordena los subniveles de menor a mayor capacidad de electrones', items: ['s', 'p', 'd', 'f'], labels: ['2', '6', '10', '14'] },
      { prompt: 'Ordena de menor a mayor número de electrones de valencia', items: ['Na: …3s¹', 'Mg: …3s²', 'B: …2s² 2p¹', 'C: …2s² 2p²', 'O: …2s² 2p⁴', 'Cl: …3s² 3p⁵'], labels: ['1', '2', '3', '4', '6', '7'] },
      { prompt: 'Ordena de menor a mayor número atómico', items: ['1s² 2s¹', '1s² 2s² 2p³', '1s² 2s² 2p⁶ 3s²', '1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹'], labels: ['Li (3)', 'N (7)', 'Mg (12)', 'K (19)'] } ] },
  ],
  g10u1l2: [
    { game: 'hunter', title: 'Cazador de cajitas ↑↓', time: 90, clues: [
      { c: 'Mi 2p tiene 3 electrones, uno en cada orbital', a: 'N' },
      { c: 'Mi 2p tiene un par y dos electrones solos', a: 'O' },
      { c: 'Mi 2p tiene solo dos electrones, ambos desapareados', a: 'C' },
      { c: 'Tengo un único electrón en el 2p', a: 'B' },
      { c: 'Mi 2p tiene dos pares y un electrón solo', a: 'F' },
      { c: 'Mis tres orbitales 2p están llenos (↑↓) y no hay más', a: 'Ne' },
      { c: 'Tengo 3 electrones desapareados en el 3p', a: 'P' },
      { c: 'Mi 3p tiene un par y dos electrones solos', a: 'S' },
      { c: 'Tengo un solo orbital y está lleno (↑↓)', a: 'He' },
      { c: 'Tengo un solo electrón, en el 1s', a: 'H' },
      { c: 'Mi 3d tiene 5 electrones y mi 4s tiene 2', a: 'Mn' },
      { c: 'Mi 3d tiene 6 electrones: un par y cuatro solos', a: 'Fe' },
      { c: 'Mi 3d tiene 3 electrones, uno en cada orbital', a: 'V' } ] },
    { game: 'word', title: 'Palabras de los orbitales', lives: 6, words: [
      { w: 'ORBITAL', h: 'Región donde es muy probable encontrar un electrón' },
      { w: 'ESPÍN', h: 'Propiedad del electrón que se dibuja como ↑ o ↓' },
      { w: 'HUND', h: 'Su regla: primero uno por caja, luego se aparean' },
      { w: 'PAULI', h: 'Su principio: máximo 2 electrones por orbital, con espín opuesto' },
      { w: 'DESAPAREADO', h: 'Así se llama un electrón que está solo en su orbital' },
      { w: 'MAGNETISMO', h: 'Propiedad que explican los electrones sin pareja, como en el hierro' },
      { w: 'SUBNIVEL', h: 'Grupo de orbitales de igual energía, como el 2p' },
      { w: 'EXCLUSIÓN', h: 'Principio de … de Pauli' } ] },
  ],
  g10u1l3: [
    { game: 'memory', title: 'Parejas nucleares', pairs: [
      ['Carbono-14', '6 protones y 8 neutrones'], ['Deuterio', 'Hidrógeno con 1 neutrón'], ['Yodo-131', 'Tratamiento de la tiroides'],
      ['Tecnecio-99m', 'Diagnóstico médico'], ['Fisión', 'Un núcleo pesado se parte'], ['Fusión', 'Núcleos livianos se unen'],
      ['Vida media', 'Se desintegra la mitad'], ['Isótopos', 'Mismo Z, distintos neutrones'] ] },
    { game: 'blitz', title: 'Contrarreloj radiactiva', time: 60, lives: 3, items: [
      { q: '¿Cuántos neutrones tiene el yodo-131? (Z = 53)', o: ['53', '78', '131', '184'], a: 1, e: '131 − 53 = 78.' },
      { q: 'El uranio-235 y el uranio-238 se diferencian en…', o: ['Protones', 'Neutrones', 'Electrones', 'El nombre del elemento'], a: 1, e: 'Son isótopos: 3 neutrones de diferencia.' },
      { q: 'El tecnecio-99m tiene vida media de 6 h. De 80 mg, tras 18 h quedan…', o: ['40 mg', '20 mg', '10 mg', '0 mg'], a: 2, e: 'Tres vidas medias: 80 → 40 → 20 → 10 mg.' },
      { q: 'El deuterio tiene…', o: ['1 protón y 1 neutrón', '2 protones', '0 neutrones', '1 protón y 2 neutrones'], a: 0, e: 'Es hidrógeno-2.' },
      { q: 'En una central nuclear la energía proviene de…', o: ['Fusión', 'Fisión', 'Combustión', 'Electrólisis'], a: 1, e: 'Núcleos pesados de uranio se parten.' },
      { q: 'El yodo-131 se usa en hospitales para…', o: ['Tratar la tiroides', 'Curar resfriados', 'Potabilizar agua', 'Endulzar alimentos'], a: 0, e: 'La tiroides acumula yodo.' },
      { q: 'El número de masa del carbono-14 es…', o: ['6', '8', '14', '20'], a: 2, e: 'Protones + neutrones = 6 + 8.' },
      { q: '¿Por qué un núcleo radiactivo emite radiación?', o: ['Porque es inestable', 'Porque tiene muchos electrones', 'Porque está caliente', 'Porque es metálico'], a: 0, e: 'Se transforma hasta ser estable.' },
      { q: 'Cloro-35 y cloro-37 tienen el mismo número de…', o: ['Neutrones', 'Protones', 'Nucleones', 'Masa'], a: 1, e: 'Mismo elemento, mismo Z = 17.' },
      { q: 'Tras 3 vidas medias queda de la muestra original…', o: ['1/3', '1/6', '1/8', 'Nada'], a: 2, e: '½ × ½ × ½ = 1/8.' } ] },
  ],
  g10u2l1: [
    { game: 'builder', title: 'Arma moléculas con octeto', targets: ['H2O', 'NH3', 'N2', 'Cl2', 'H2O2', 'CH3OH'], palette: ['H', 'C', 'N', 'O', 'Cl'] },
    { game: 'blitz', title: 'Contrarreloj de Lewis', time: 60, lives: 3, items: [
      { q: '¿Cuántos pares libres hay en total en el N₂?', o: ['0', '1', '2', '4'], a: 2, e: 'Triple enlace y un par libre en cada nitrógeno.' },
      { q: 'En el Cl₂, los átomos se unen con un enlace…', o: ['Sencillo', 'Doble', 'Triple', 'Iónico'], a: 0, e: 'Cada Cl tiene 7 e⁻ y comparte 1 par.' },
      { q: '¿Cuántos electrones de valencia tiene el carbono?', o: ['2', '4', '6', '8'], a: 1, e: '2s² 2p²: forma 4 enlaces.' },
      { q: 'En el CO₂ (O=C=O), el carbono tiene…', o: ['4 pares libres', '2 dobles enlaces y 0 pares libres', '1 triple enlace', '2 pares libres'], a: 1, e: '4 pares compartidos = 8 electrones.' },
      { q: 'El hidrógeno queda estable con … electrones', o: ['1', '2', '4', '8'], a: 1, e: 'Como el helio.' },
      { q: '¿Cuántos pares libres tiene el cloro en el HCl?', o: ['1', '2', '3', '4'], a: 2, e: '1 par compartido + 3 libres = 8 electrones.' },
      { q: 'En el CH₄, el carbono tiene…', o: ['4 enlaces y 0 pares libres', '2 enlaces y 2 pares libres', '3 enlaces y 1 par libre', '4 pares libres'], a: 0, e: 'Cuatro pares compartidos.' },
      { q: 'Un enlace covalente sencillo es…', o: ['Un par de electrones compartido', 'Un electrón', 'Dos pares compartidos', 'Un protón compartido'], a: 0, e: 'Se dibuja como una raya.' },
      { q: 'Entre los dos N del N₂ hay un enlace…', o: ['Sencillo', 'Doble', 'Triple', 'Iónico'], a: 2, e: 'Cada N comparte 3 electrones.' },
      { q: 'En el H₂O₂ (H–O–O–H), cada oxígeno tiene … pares libres', o: ['0', '1', '2', '3'], a: 2, e: '2 enlaces + 2 pares libres = 8.' },
      { q: 'El oxígeno (6 e⁻ de valencia) completa el octeto con … enlaces sencillos', o: ['1', '2', '3', '4'], a: 1, e: '6 + 2 compartidos = 8.' } ] },
  ],
  g10u2l2: [
    { game: 'order', title: 'La escalera de la electronegatividad', time: 90, rounds: [
      { prompt: 'Ordena de menor a mayor electronegatividad', items: ['K', 'H', 'C', 'Cl', 'O', 'F'], labels: ['0,8', '2,2', '2,5', '3,2', '3,4', '4,0'] },
      { prompt: 'Ordena los enlaces de menor a mayor ΔEN', items: ['Cl–Cl', 'C–H', 'H–Cl', 'O–H', 'Na–Cl', 'K–F'], labels: ['0', '0,3', '1,0', '1,2', '2,3', '3,2'] },
      { prompt: 'Periodo 2: ordena de menor a mayor electronegatividad', items: ['Li', 'Be', 'B', 'C', 'N', 'O'], labels: ['1,0', '1,6', '2,0', '2,5', '3,0', '3,4'] } ] },
    { game: 'catcher', title: 'Atrapa los iónicos', time: 45, lives: 3,
      rule: 'Atrapa solo los compuestos iónicos',
      good: ['KCl', 'MgO', 'CaCl₂', 'LiF', 'Na₂O', 'KBr', 'CaO', 'NaF', 'MgCl₂'],
      bad: ['H₂O', 'CH₄', 'CO₂', 'NH₃', 'O₂', 'Cl₂', 'HCl', 'N₂', 'CCl₄'] },
  ],
  g10u2l3: [
    { game: 'memory', title: 'Parejas de geometrías', pairs: [
      ['CH₄', 'Tetraédrica, 109,5°'], ['NH₃', 'Piramidal, 107°'], ['H₂O', 'Angular, 104,5°'], ['BF₃', 'Trigonal plana, 120°'],
      ['CO₂', 'Lineal, 180°'], ['RPECV', 'Los pares se repelen'], ['Par libre', 'Empuja más y cierra ángulos'] ] },
    { game: 'sorter', title: 'Polar o apolar: decide la forma', time: 60, bins: ['Polar', 'Apolar'], items: [
      ['H₂O', 0], ['NH₃', 0], ['CH₄', 1], ['CO₂', 1], ['BF₃', 1], ['HCl', 0], ['CCl₄', 1], ['H₂S', 0],
      ['SO₂', 0], ['O₂', 1], ['N₂', 1], ['CH₃Cl', 0], ['HF', 0], ['BeCl₂', 1], ['SO₃', 1], ['NF₃', 0] ] },
  ],
  g10u3l1: [
    { game: 'builder', title: 'Fábrica de óxidos', targets: ['CaO', 'CO2', 'CO', 'SO2', 'SO3', 'NO2'], palette: ['C', 'N', 'O', 'S', 'Ca'] },
    { game: 'catcher', title: 'Atrapa los óxidos ácidos', time: 45, lives: 3,
      rule: 'Atrapa solo los óxidos ácidos (no metal + oxígeno)',
      good: ['SO₂', 'N₂O₅', 'Cl₂O₇', 'SiO₂', 'Cl₂O', 'N₂O₃', 'SeO₂', 'CO₂', 'P₂O₃'],
      bad: ['K₂O', 'Li₂O', 'BaO', 'FeO', 'CuO', 'Cu₂O', 'NiO', 'SrO'] },
  ],
  g10u3l2: [
    { game: 'balancer', title: 'Óxido + agua: balancea', rx: [
      { r: ['Na2O', 'H2O'], p: ['NaOH'], c: [1, 1, 2] },
      { r: ['MgO', 'H2O'], p: ['Mg(OH)2'], c: [1, 1, 1] },
      { r: ['Fe2O3', 'H2O'], p: ['Fe(OH)3'], c: [1, 3, 2] },
      { r: ['Al2O3', 'H2O'], p: ['Al(OH)3'], c: [1, 3, 2] },
      { r: ['CO2', 'H2O'], p: ['H2CO3'], c: [1, 1, 1] },
      { r: ['N2O5', 'H2O'], p: ['HNO3'], c: [1, 1, 2] },
      { r: ['P2O5', 'H2O'], p: ['H3PO4'], c: [1, 3, 2] },
      { r: ['Cl2O7', 'H2O'], p: ['HClO4'], c: [1, 1, 2] },
      { r: ['H2', 'Cl2'], p: ['HCl'], c: [1, 1, 2] } ] },
    { game: 'word', title: 'Palabra secreta de la nomenclatura', lives: 6, words: [
      { w: 'HIDRÓXIDO', h: 'Base que resulta de óxido básico + agua, como el Ca(OH)₂' },
      { w: 'OXÁCIDO', h: 'Ácido con H, un no metal y oxígeno, como el H₂SO₄' },
      { w: 'HIDRÁCIDO', h: 'Ácido sin oxígeno, como el HCl' },
      { w: 'HIDROXILO', h: 'Nombre del grupo OH que tienen todas las bases de esta lección' },
      { w: 'SULFÚRICO', h: 'Ácido H₂SO₄, el de la batería del carro' },
      { w: 'CLORHÍDRICO', h: 'Ácido HCl, presente en el estómago' },
      { w: 'NÍTRICO', h: 'Ácido HNO₃, uno de los que forman la lluvia ácida' },
      { w: 'CARBÓNICO', h: 'Ácido H₂CO₃ que se forma al disolver CO₂ en agua' } ] },
  ],
  g10u3l3: [
    { game: 'sorter', title: '¿-uro, -ato o -ito?', time: 60, bins: ['Sal -uro', 'Sal -ato', 'Sal -ito'], items: [
      ['Ácido clorhídrico', 0], ['Ácido sulfúrico', 1], ['Ácido sulfuroso', 2], ['Ácido nítrico', 1], ['Ácido nitroso', 2],
      ['Ácido bromhídrico', 0], ['Ácido carbónico', 1], ['Ácido fosfórico', 1], ['Ácido hipocloroso', 2],
      ['Ácido fluorhídrico', 0], ['Ácido sulfhídrico', 0], ['Ácido cloroso', 2], ['Ácido perclórico', 1], ['Ácido yodhídrico', 0] ] },
    { game: 'catcher', title: 'Atrapa las oxisales', time: 45, lives: 3,
      rule: 'Atrapa solo las oxisales (llevan oxígeno)',
      good: ['K₂SO₄', 'NaNO₃', 'CaSO₄', 'Na₂CO₃', 'KClO₃', 'MgSO₄', 'NaClO', 'Ca₃(PO₄)₂', 'KNO₂'],
      bad: ['KCl', 'NaBr', 'CaCl₂', 'MgF₂', 'K₂S', 'NaI', 'AgCl', 'CuCl₂', 'LiF'] },
  ],
  g10u4l1: [
    { game: 'balancer', title: 'Balancea cada tipo de reacción', rx: [
      { r: ['Al', 'O2'], p: ['Al2O3'], c: [4, 3, 2] },
      { r: ['H2O'], p: ['H2', 'O2'], c: [2, 2, 1] },
      { r: ['SO2', 'O2'], p: ['SO3'], c: [2, 1, 2] },
      { r: ['Mg', 'HCl'], p: ['MgCl2', 'H2'], c: [1, 2, 1, 1] },
      { r: ['Na', 'H2O'], p: ['NaOH', 'H2'], c: [2, 2, 2, 1] },
      { r: ['Zn', 'CuSO4'], p: ['ZnSO4', 'Cu'], c: [1, 1, 1, 1] },
      { r: ['CaCl2', 'Na2CO3'], p: ['CaCO3', 'NaCl'], c: [1, 1, 1, 2] },
      { r: ['FeCl3', 'NaOH'], p: ['Fe(OH)3', 'NaCl'], c: [1, 3, 1, 3] } ] },
    { game: 'truefalse', title: 'Redox: ¿verdad o mito?', time: 60, lives: 3, items: [
      { s: 'En la oxidación, un átomo pierde electrones.', a: true, e: 'Oxidación = pérdida de electrones.' },
      { s: 'La combustión es una reacción redox.', a: true, e: 'El combustible se oxida y el oxígeno se reduce.' },
      { s: 'En una descomposición, dos sustancias se unen para formar una.', a: false, e: 'Eso es una síntesis; en la descomposición un compuesto se separa.' },
      { s: 'Zn + CuSO₄ → ZnSO₄ + Cu es un desplazamiento simple.', a: true, e: 'El zinc reemplaza al cobre.' },
      { s: 'La neutralización es un tipo de doble desplazamiento.', a: true, e: 'Los iones se intercambian: AB + CD → AD + CB.' },
      { s: 'En una redox, una especie puede oxidarse sin que otra se reduzca.', a: false, e: 'Los electrones que pierde una los gana otra.' },
      { s: 'La corrosión del hierro es una reacción redox.', a: true, e: 'El hierro se oxida a Fe³⁺.' },
      { s: 'Una precipitación produce un gas.', a: false, e: 'Produce un sólido insoluble.' },
      { s: 'En 2 H₂ + O₂ → 2 H₂O, el hidrógeno se oxida.', a: true, e: 'Pasa de 0 a +1: pierde electrones.' },
      { s: 'HCl + NaOH → NaCl + H₂O es una reacción redox.', a: false, e: 'Ningún número de oxidación cambia.' },
      { s: 'Reducción significa ganar electrones.', a: true, e: 'Su número de oxidación baja.' },
      { s: 'CaO + CO₂ → CaCO₃ es una descomposición.', a: false, e: 'Dos sustancias forman una: es una síntesis.' } ] },
  ],
  g10u4l2: [
    { game: 'memory', title: 'Parejas de masa molar', pairs: [
      ['H₂O', '18 g/mol'], ['CO₂', '44 g/mol'], ['CH₄', '16 g/mol'], ['NH₃', '17 g/mol'],
      ['NaCl', '58,5 g/mol'], ['O₂', '32 g/mol'], ['C₆H₁₂O₆', '180 g/mol'], ['1 mol', '6,02 × 10²³ partículas'] ] },
    { game: 'hunter', title: '¿Cuánto pesa un mol de mí?', time: 90, clues: [
      { c: 'Un mol de mis átomos pesa 12 g', a: 'C' }, { c: 'Un mol de mis átomos pesa 16 g', a: 'O' },
      { c: 'Un mol de mis átomos pesa 1 g', a: 'H' }, { c: 'Un mol de mis átomos pesa 23 g', a: 'Na' },
      { c: 'Un mol de mis átomos pesa 14 g', a: 'N' }, { c: 'Un mol de mis átomos pesa 32 g', a: 'S' },
      { c: 'Un mol de mis átomos pesa 35,5 g', a: 'Cl' }, { c: 'Un mol de mis átomos pesa 55,8 g', a: 'Fe' },
      { c: 'Un mol de mis átomos pesa 24,3 g', a: 'Mg' }, { c: 'Un mol de mis átomos pesa 27 g', a: 'Al' },
      { c: 'Un mol de mis átomos pesa 4 g: soy gas noble', a: 'He' }, { c: 'Un mol de mis átomos pesa 63,5 g', a: 'Cu' },
      { c: 'Un mol de mis átomos pesa 39,1 g', a: 'K' }, { c: '2 mol de mis átomos pesan 40,4 g: soy gas noble', a: 'Ne' },
      { c: 'Medio mol de mis átomos pesa 32,7 g', a: 'Zn' } ] },
  ],
  g10u4l3: [
    { game: 'blitz', title: 'Contrarreloj estequiométrica', time: 60, lives: 3, items: [
      { q: 'CH₄ + 2 O₂ → CO₂ + 2 H₂O. ¿Mol de O₂ para quemar 3 mol de CH₄?', o: ['3', '6', '2', '9'], a: 1, e: 'Relación 1 : 2 → 3 × 2 = 6.' },
      { q: '2 H₂ + O₂ → 2 H₂O. Con 2 mol de H₂ y 5 mol de O₂, el reactivo límite es…', o: ['H₂', 'O₂', 'Ninguno', 'El agua'], a: 0, e: '2 mol de H₂ solo necesitan 1 mol de O₂: sobra O₂.' },
      { q: 'N₂ + 3 H₂ → 2 NH₃. Con 1 mol de N₂ y 6 mol de H₂, el límite es…', o: ['N₂', 'H₂', 'NH₃', 'Ninguno'], a: 0, e: '1 mol de N₂ usa solo 3 mol de H₂.' },
      { q: '2 H₂ + O₂ → 2 H₂O. ¿Cuántos gramos de agua salen de 4 g de H₂?', o: ['18 g', '36 g', '4 g', '72 g'], a: 1, e: '4 g = 2 mol de H₂ → 2 mol de H₂O × 18 = 36 g.' },
      { q: 'CH₄ + 2 O₂ → CO₂ + 2 H₂O. De 16 g de CH₄ se obtienen … de CO₂', o: ['16 g', '44 g', '22 g', '88 g'], a: 1, e: '1 mol de CH₄ → 1 mol de CO₂ = 44 g.' },
      { q: 'El reactivo en exceso es el que…', o: ['Se acaba primero', 'Sobra al final', 'Nunca reacciona', 'Es un producto'], a: 1, e: 'El límite se acaba primero; el otro sobra.' },
      { q: 'La masa de reactivos que reaccionan es igual a la de productos porque…', o: ['Se conservan los átomos', 'Se crean átomos', 'Los gases no pesan', 'Es casualidad'], a: 0, e: 'Ley de conservación de la masa.' },
      { q: 'C + O₂ → CO₂. Con 12 g de C y 64 g de O₂, sobran…', o: ['32 g de O₂', '12 g de C', 'Nada', '44 g de CO₂'], a: 0, e: '1 mol de C usa 1 mol de O₂ (32 g); sobra 1 mol de O₂.' },
      { q: '2 Na + Cl₂ → 2 NaCl. ¿Mol de NaCl con 0,5 mol de Cl₂ y Na suficiente?', o: ['0,5', '1', '2', '0,25'], a: 1, e: 'Relación 1 : 2 → 0,5 × 2 = 1 mol.' },
      { q: 'Para pasar de gramos a moles se divide entre…', o: ['El coeficiente', 'La masa molar', '6,02 × 10²³', 'El volumen'], a: 1, e: 'moles = masa ÷ masa molar.' } ] },
    { game: 'order', title: 'La ruta estequiométrica', time: 90, rounds: [
      { prompt: 'Ordena los pasos de un cálculo estequiométrico', items: ['Balancear la ecuación', 'Pasar la masa a moles', 'Aplicar la relación de coeficientes', 'Obtener los moles del producto', 'Pasar los moles a masa'] },
      { prompt: 'Ordena los pasos para hallar el reactivo límite', items: ['Balancear la ecuación', 'Pasar cada masa a moles', 'Comparar con la proporción de coeficientes', 'Identificar el que se acaba primero', 'Calcular el producto con el límite'] },
      { prompt: 'N₂ + 3 H₂ → 2 NH₃ con 2 mol de N₂: ordena de menor a mayor número de moles', items: ['N₂ que reacciona', 'NH₃ que se forma', 'H₂ que reacciona'], labels: ['2 mol', '4 mol', '6 mol'] },
      { prompt: 'CH₄ + 2 O₂ → CO₂ + 2 H₂O con 1 mol de CH₄: ordena de menor a mayor masa', items: ['CH₄ que reacciona', 'H₂O que se forma', 'CO₂ que se forma', 'O₂ que reacciona'], labels: ['16 g', '36 g', '44 g', '64 g'] } ] },
  ],

  /* ===================== GRADO 11° ===================== */
  g11u1l1: [
    { game: 'sorter', title: '¿Acelera o frena la reacción?', time: 60, bins: ['Acelera', 'Frena'], items: [
      ['Subir la temperatura', 0], ['Guardar en la nevera', 1], ['Panela en polvo', 0], ['Añadir un catalizador', 0],
      ['Diluir el reactivo', 1], ['Enzimas digestivas', 0], ['Leña en tronco entero', 1], ['Leña en astillas', 0],
      ['Más concentración', 0], ['Congelar la carne', 1], ['Masticar bien', 0], ['Cocinar en olla a presión', 0],
      ['Conservantes en el pan', 1], ['Pastilla entera, sin moler', 1] ] },
    { game: 'word', title: 'Palabras de la cinética', lives: 6, words: [
      { w: 'CATALIZADOR', h: 'Sustancia que acelera una reacción y se recupera al final' },
      { w: 'COLISIÓN', h: 'Choque entre partículas; sin él no hay reacción' },
      { w: 'ACTIVACIÓN', h: 'Energía de …: la barrera mínima para que un choque sea efectivo' },
      { w: 'ENZIMA', h: 'Catalizador natural del cuerpo, como la amilasa de la saliva' },
      { w: 'TEMPERATURA', h: 'Al subirla, los choques son más frecuentes y energéticos' },
      { w: 'SUPERFICIE', h: '… de contacto: es mayor en un sólido en polvo' },
      { w: 'CONCENTRACIÓN', h: 'Más partículas por volumen, más choques' },
      { w: 'ORIENTACIÓN', h: 'Además de energía, las partículas deben chocar con la … adecuada' } ] },
  ],
  g11u1l2: [
    { game: 'reactor', title: 'Operador de la planta Haber', mode: 'equilibrium' },
    { game: 'sorter', title: 'Le Châtelier: N₂ + 3H₂ ⇌ 2NH₃ (exotérmica)', time: 60, bins: ['Hacia productos', 'Hacia reactivos', 'No se desplaza'], items: [
      ['Agregar N₂', 0], ['Retirar NH₃', 0], ['Subir la presión', 0], ['Enfriar', 0], ['Agregar H₂', 0], ['Reducir el volumen', 0],
      ['Calentar', 1], ['Bajar la presión', 1], ['Agregar NH₃', 1], ['Retirar H₂', 1], ['Retirar N₂', 1], ['Aumentar el volumen', 1],
      ['Agregar un catalizador', 2], ['Esperar más tiempo', 2] ] },
  ],
  g11u2l1: [
    { game: 'builder', title: 'Arma y mira: sp³, sp² o sp', targets: ['CH4', 'C2H6', 'C2H4', 'C2H2', 'H2CO', 'CO2'], palette: ['C', 'H', 'O'] },
    { game: 'sorter', title: 'Clasifica la hibridación', time: 60, bins: ['sp³', 'sp²', 'sp'], items: [
      ['C del metano', 0], ['C del etano', 0], ['C del propano', 0], ['C del metanol', 0], ['C del diamante', 0],
      ['C del eteno', 1], ['C del formaldehído', 1], ['C=O de la acetona', 1], ['C del benceno', 1], ['C del grafito', 1],
      ['C del etino', 2], ['C del CO₂', 2], ['C del HCN', 2] ] },
  ],
  g11u2l2: [
    { game: 'catcher', title: 'Atrapa los alquenos', time: 45, lives: 3,
      rule: 'Atrapa solo los alquenos (tienen C=C)',
      good: ['Eteno', 'Propeno', '1-buteno', 'Penteno', 'Hexeno', 'CH₂=CH₂', 'CH₂=CH–CH₃', 'Etileno'],
      bad: ['Etano', 'Etino', 'Propano', 'Butano', 'Metano', 'Propino', 'CH≡CH', 'Hexano', 'C₂H₆'] },
    { game: 'memory', title: 'Parejas de hidrocarburos', pairs: [
      ['CH₄', 'Metano'], ['C₂H₆', 'Etano'], ['C₃H₈', 'Propano'], ['C₄H₁₀', 'Butano'],
      ['C₃H₆', 'Propeno'], ['C₃H₄', 'Propino'], ['C₆H₁₄', 'Hexano'], ['C₅H₁₀', 'Penteno'] ] },
  ],
  g11u2l3: [
    { game: 'sorter', title: '¿Qué tipo de isomería?', time: 60, bins: ['De cadena', 'De posición', 'De función'], items: [
      ['Butano / metilpropano', 0], ['Pentano / metilbutano', 0], ['Pentano / dimetilpropano', 0], ['Hexano / 2-metilpentano', 0],
      ['1-propanol / 2-propanol', 1], ['1-buteno / 2-buteno', 1], ['1-butanol / 2-butanol', 1], ['2-pentanona / 3-pentanona', 1],
      ['Etanol / dimetil éter', 2], ['Propanal / propanona', 2], ['Butanal / butanona', 2], ['1-butanol / dietil éter', 2] ] },
    { game: 'blitz', title: 'Contrarreloj de isómeros', time: 60, lives: 3, items: [
      { q: '¿Cuál es isómero del butano (C₄H₁₀)?', o: ['Metilpropano', 'Propano', 'Buteno', 'Pentano'], a: 0, e: 'También es C₄H₁₀, pero ramificado.' },
      { q: 'Etanol (líquido) y dimetil éter (gas) tienen igual…', o: ['Fórmula molecular', 'Punto de ebullición', 'Grupo funcional', 'Estructura'], a: 0, e: 'Ambos son C₂H₆O.' },
      { q: '1-buteno y 2-buteno son isómeros de…', o: ['Cadena', 'Posición', 'Función', 'No son isómeros'], a: 1, e: 'Cambia la posición del doble enlace.' },
      { q: '¿Cuántos isómeros estructurales tiene el C₄H₁₀?', o: ['1', '2', '3', '4'], a: 1, e: 'Butano y metilpropano.' },
      { q: '¿Cuántos isómeros estructurales tiene el C₅H₁₂?', o: ['2', '3', '4', '5'], a: 1, e: 'Pentano, metilbutano y dimetilpropano.' },
      { q: 'Propanal (aldehído) y propanona (cetona) son isómeros de…', o: ['Cadena', 'Posición', 'Función', 'No son isómeros'], a: 2, e: 'Misma fórmula, C₃H₆O, distinto grupo funcional.' },
      { q: '¿Son isómeros el metano y el etano?', o: ['Sí, de cadena', 'No: tienen distinta fórmula molecular', 'Sí, de función', 'Sí, de posición'], a: 1, e: 'CH₄ y C₂H₆ no tienen los mismos átomos.' },
      { q: 'El 1-propanol y el 2-propanol se diferencian en…', o: ['La posición del –OH', 'El número de carbonos', 'La fórmula molecular', 'El grupo funcional'], a: 0, e: 'Ambos son alcoholes C₃H₈O.' },
      { q: 'Entre dos isómeros de cadena, el más ramificado suele hervir…', o: ['A menor temperatura', 'A mayor temperatura', 'A la misma', 'Nunca hierve'], a: 0, e: 'Butano: −0,5 °C; isobutano: −12 °C.' },
      { q: '¿Qué fórmula comparten el etanol y el dimetil éter?', o: ['C₂H₆O', 'C₂H₆', 'CH₄O', 'C₂H₄O₂'], a: 0, e: 'Por eso son isómeros de función.' } ] },
  ],
  g11u3l1: [
    { game: 'builder', title: 'Del alcano al alcohol', targets: ['CH4', 'CH3OH', 'C2H6', 'C2H5OH', 'C3H7OH'], palette: ['C', 'H', 'O'] },
    { game: 'order', title: 'Ordena los alcoholes', time: 90, rounds: [
      { prompt: 'Ordena de menor a mayor punto de ebullición', items: ['Metanol', 'Etanol', '1-propanol', '1-butanol'], labels: ['65 °C', '78 °C', '97 °C', '118 °C'] },
      { prompt: 'Masas parecidas: ordena de menor a mayor punto de ebullición', items: ['Propano', 'Dimetil éter', 'Etanol'], labels: ['−42 °C', '−24 °C', '78 °C'] },
      { prompt: 'Ordena de más a menos soluble en agua', items: ['Etanol', '1-butanol', '1-pentanol', '1-hexanol'], labels: ['Se mezcla en todo', '≈ 7 g/100 mL', '≈ 2 g/100 mL', '≈ 0,6 g/100 mL'] },
      { prompt: 'Ordena los pasos para producir bioetanol de caña', items: ['Cortar y moler la caña', 'Extraer el jugo azucarado', 'Fermentar con levaduras', 'Destilar', 'Mezclar con la gasolina'] } ] },
  ],
  g11u3l2: [
    { game: 'catcher', title: 'Atrapa las cetonas', time: 45, lives: 3,
      rule: 'Atrapa solo las cetonas (C=O en medio)',
      good: ['Propanona', 'Butanona', 'Acetona', '2-pentanona', '3-pentanona', 'CH₃–CO–CH₃', 'CH₃–CO–C₂H₅', '2-hexanona'],
      bad: ['Metanal', 'Etanal', 'Propanal', 'Butanal', 'Formaldehído', 'CH₃–CHO', 'H–CHO', 'Etanol', 'Ácido acético'] },
    { game: 'truefalse', title: 'Carbonilo: ¿verdad o mito?', time: 60, lives: 3, items: [
      { s: 'Aldehídos y cetonas tienen el grupo carbonilo C=O.', a: true, e: 'Se diferencian en dónde está.' },
      { s: 'En una cetona, el C=O está al final de la cadena.', a: false, e: 'Al final está en los aldehídos; en las cetonas, en medio.' },
      { s: 'La acetona del quitaesmalte es una cetona.', a: true, e: 'Es la propanona.' },
      { s: 'El metanal (formaldehído) se usa para conservar muestras biológicas.', a: true, e: 'Es un aldehído.' },
      { s: 'Los aldehídos terminan en -ol.', a: false, e: 'Terminan en -al; -ol es de los alcoholes.' },
      { s: 'La propanona tiene 3 carbonos.', a: true, e: 'Prop- = 3 carbonos.' },
      { s: 'Existe una cetona de un solo carbono, la "metanona".', a: false, e: 'En una cetona el C=O va entre dos carbonos: mínimo 3 carbonos.' },
      { s: 'El grupo –CHO es característico de los aldehídos.', a: true, e: 'Es el carbonilo al final de la cadena.' },
      { s: 'Propanal y propanona tienen la misma fórmula molecular.', a: true, e: 'Ambos son C₃H₆O: isómeros de función.' },
      { s: 'El carbonilo tiene un enlace triple C≡O.', a: false, e: 'Es un enlace doble, C=O.' },
      { s: 'La butanona es un aldehído.', a: false, e: 'La terminación -ona indica cetona.' } ] },
  ],
  g11u3l3: [
    { game: 'builder', title: 'Laboratorio de ácidos, ésteres y aminas', targets: ['HCOOH', 'CH3COOH', 'C2H5OH', 'CH3COOC2H5', 'CH3NH2'], palette: ['C', 'H', 'N', 'O'] },
    { game: 'memory', title: 'Parejas de olores y grupos', pairs: [
      ['–COOH', 'Ácido carboxílico'], ['–COO–', 'Éster'], ['–NH₂', 'Amina'], ['Ácido acético', 'Vinagre'],
      ['Ácido fórmico', 'Picadura de hormiga'], ['Acetato de isoamilo', 'Olor a banano'], ['Trimetilamina', 'Olor a pescado'], ['Ácido + alcohol', 'Éster + agua'] ] },
  ],
  g11u4l1: [
    { game: 'catcher', title: 'Atrapa las proteínas', time: 45, lives: 3,
      rule: 'Atrapa solo las proteínas',
      good: ['Colágeno', 'Hemoglobina', 'Insulina', 'Caseína', 'Albúmina', 'Pepsina', 'Anticuerpos', 'Miosina', 'Lactasa'],
      bad: ['Almidón', 'Glucosa', 'Celulosa', 'Sacarosa', 'Colesterol', 'Aceite de oliva', 'ADN', 'ARN', 'Glucógeno', 'Triglicérido'] },
    { game: 'word', title: 'Palabras de la vida', lives: 6, words: [
      { w: 'CARBOHIDRATO', h: 'Biomolécula de energía rápida, como la glucosa y el almidón' },
      { w: 'LÍPIDO', h: 'Grasa o aceite: reserva de energía y parte de las membranas' },
      { w: 'PROTEÍNA', h: 'Biomolécula formada por aminoácidos; da estructura y forma enzimas' },
      { w: 'AMINOÁCIDO', h: 'Unidad que se repite en las cadenas de las proteínas' },
      { w: 'ENZIMA', h: 'Proteína que actúa como catalizador en el cuerpo' },
      { w: 'ALMIDÓN', h: 'Carbohidrato de reserva de la papa, el arroz y la yuca' },
      { w: 'GLUCOSA', h: 'Azúcar sencillo, principal combustible de las células' },
      { w: 'NUCLEICO', h: 'Ácido …: así se clasifican el ADN y el ARN' } ] },
  ],
  g11u4l2: [
    { game: 'memory', title: 'Parejas de polímeros', pairs: [
      ['Polietileno', 'Monómero: eteno'], ['PET', 'Botellas de gaseosa'], ['PVC', 'Tuberías'], ['Poliestireno', 'Icopor'],
      ['Nailon', 'Medias y cuerdas'], ['Celulosa', 'Papel y madera'], ['Caucho natural', 'Látex de árbol'], ['Almidón', 'Cadenas de glucosa'] ] },
    { game: 'truefalse', title: 'Plásticos: ¿verdad o mito?', time: 60, lives: 3, items: [
      { s: 'Un polímero está formado por muchas unidades repetidas.', a: true, e: 'Esas unidades son los monómeros.' },
      { s: 'Todos los polímeros son sintéticos.', a: false, e: 'Celulosa, almidón, caucho y proteínas son naturales.' },
      { s: 'El polietileno se forma uniendo moléculas de eteno.', a: true, e: 'El doble enlace se abre para enlazar la cadena.' },
      { s: 'Las proteínas son polímeros.', a: true, e: 'Son cadenas de aminoácidos.' },
      { s: 'El icopor es poliestireno.', a: true, e: 'Es poliestireno expandido.' },
      { s: 'Los plásticos comunes se degradan en pocos meses.', a: false, e: 'Muchos tardan cientos de años.' },
      { s: 'Se pueden reciclar todos los plásticos juntos, sin separarlos.', a: false, e: 'Cada tipo de polímero se procesa diferente.' },
      { s: 'El número dentro del triángulo de reciclaje indica el tipo de plástico.', a: true, e: 'Por ejemplo, 1 es PET y 3 es PVC.' },
      { s: 'El monómero del polietileno es el metano.', a: false, e: 'Es el eteno; el metano no tiene doble enlace.' },
      { s: 'La Ley 2232 de 2022 busca reducir los plásticos de un solo uso en Colombia.', a: true, e: 'Plantea su eliminación gradual.' },
      { s: 'La seda y el nailon son polímeros naturales.', a: false, e: 'La seda es natural; el nailon es sintético.' } ] },
  ],
  g11u4l3: [
    { game: 'balancer', title: 'Balancea la combustión', rx: [
      { r: ['CH4', 'O2'], p: ['CO2', 'H2O'], c: [1, 2, 1, 2] },
      { r: ['C2H6', 'O2'], p: ['CO2', 'H2O'], c: [2, 7, 4, 6] },
      { r: ['C2H2', 'O2'], p: ['CO2', 'H2O'], c: [2, 5, 4, 2] },
      { r: ['CH3OH', 'O2'], p: ['CO2', 'H2O'], c: [2, 3, 2, 4] },
      { r: ['C7H16', 'O2'], p: ['CO2', 'H2O'], c: [1, 11, 7, 8] },
      { r: ['C8H18', 'O2'], p: ['CO2', 'H2O'], c: [2, 25, 16, 18] },
      { r: ['CH4', 'O2'], p: ['CO', 'H2O'], c: [2, 3, 2, 4] },
      { r: ['C', 'O2'], p: ['CO'], c: [2, 1, 2] } ] },
    { game: 'order', title: 'La torre de destilación', time: 90, rounds: [
      { prompt: 'Ordena las fracciones del petróleo de menor a mayor punto de ebullición', items: ['Gases', 'Gasolina', 'Queroseno', 'Diésel', 'Asfaltos'] },
      { prompt: 'Ordena los combustibles de menor a mayor número de carbonos', items: ['Metano (gas natural)', 'Propano (cilindro)', 'Butano (encendedor)', 'Octano (gasolina)'], labels: ['1 C', '3 C', '4 C', '8 C'] },
      { prompt: 'Ordena de menor a mayor CO₂ liberado al quemar una molécula', items: ['Metano', 'Etanol', 'Propano', 'Butano', 'Octano'], labels: ['1 CO₂', '2 CO₂', '3 CO₂', '4 CO₂', '8 CO₂'] } ] },
  ],
};
